### ISSUE TITLE
About inference time and GPU requirements

### ISSUE THREAD

**Issue by shoegazerstella** [facebookresearch/demucs#1]
I am trying demucs on a GeForce GTX 1080 but I have this error:

```
CUDA_VISIBLE_DEVICES=0 python3 -m demucs.separate --dl -n demucs test.mp3 
  0%|                                                                                                                    | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/stella/.conda/envs/demucs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/stella/.conda/envs/demucs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/Data/stella/demucs/demucs/separate.py", line 132, in <module>
    main()
  File "/mnt/Data/stella/demucs/demucs/separate.py", line 121, in main
    sources = apply_model(model, wav, shifts=args.shifts, split=args.split)
  File "/mnt/Data/stella/demucs/demucs/utils.py", line 121, in apply_model
    shifted_out = apply_model(model, shifted)
  File "/mnt/Data/stella/demucs/demucs/utils.py", line 130, in apply_model
    out = model(padded.unsqueeze(0))[0]
  File "/home/stella/.conda/envs/demucs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Data/stella/demucs/demucs/model.py", line 201, in forward
    x = self.lstm(x)
  File "/home/stella/.conda/envs/demucs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Data/stella/demucs/demucs/model.py", line 23, in forward
    x = self.lstm(x)[0]
  File "/home/stella/.conda/envs/demucs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/stella/.conda/envs/demucs/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 564, in forward
    return self.forward_tensor(input, hx)
  File "/home/stella/.conda/envs/demucs/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 543, in forward_tensor
    output, hidden = self.forward_impl(input, hx, batch_sizes, max_batch_size, sorted_indices)
  File "/home/stella/.conda/envs/demucs/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 526, in forward_impl
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA out of memory. Tried to allocate 1.74 GiB (GPU 0; 7.92 GiB total capacity; 4.42 GiB already allocated; 1.56 GiB free; 992.21 MiB cached)
```
Is there some specific gpu requirement for demucs? Also, what's the avg inference time for this model?
`tasnet` works fine on gpu and takes about 30s on a 3.27 minutes audio file.

On cpu I was unable to use both models, they seem to run forever.
I tried with a 2 seconds audio and it works but takes quite a long time.

``` 
time python3 -m demucs.separate --dl -n tasnet --split /Users/stella/Desktop/demucs_test/test.mp3
  0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]
predicting....
done prediction now saving data
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [01:15<00:00, 75.66s/it]

real	1m16.184s
user	1m5.964s
sys	0m16.211s
(demucs) stella$ time python3 -m demucs.separate --dl -n demucs /Users/stella/Desktop/demucs_test/test.mp3
  0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]
predicting....
done prediction now saving data
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:16<00:00, 16.65s/it]

real	0m19.132s
user	0m56.393s
sys	0m4.840s
```

**Comment by adefossez** [comment]
When running on CPU use `--shifts=0`, this will make performance a bit worse for Demucs but around real time separation speed. Otherwise separating 1 second will take 10 seconds. This option does not impact the quality of Tasnet, so that you can always generate with `--shifts=0` for Tasnet. The `--shifts` options randomly shift the input by multiple values and average the shifted back predictions, the default value is 10. While this is acceptable on GPU, it is another story on CPU...

On GPU, with Demucs try adding the `--split` option. This will first split the track in chunks of 16 seconds, otherwise it tries to separate the entire track at once. I should probably make that the default :)

**Comment by TronRin** [comment]
Okay, an update. I managed to install the gpu one by changing cudatoolkit ver to 10.1 but it still gave the error, but i finally figured out i should have addec '-d cpu' to my commandline. But the problem with cuda is that it uses my intergrated gpu by intel instead of my main gpu which Geforce RTX 2060. Or so I believe is the cause of the error.

**Comment by arnavmehta7** [comment]
Voice + Others is highly in need!
