### ISSUE TITLE
GPU problem in Google Colab

### ISSUE THREAD

**Issue by charlyromero** [facebookresearch/demucs#108]
**Hello, the Google Colab project link is this:** [https://colab.research.google.com/drive/1x20HORmB5Q1bRaXEWABVM6S8e7uBAxzF](https://colab.research.google.com/drive/1x20HORmB5Q1bRaXEWABVM6S8e7uBAxzF)

**When I run the command to start the process to the music file:**
!python3 -m demucs.separate --dl -n demucs -d cuda example.mp3

**It returns the following error:**
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/demucs/demucs/separate.py", line 222, in <module>
    main()
  File "/content/demucs/demucs/separate.py", line 184, in main
    model = load_model(model_path).to(args.device)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 443, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 225, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 441, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 149, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 63, in _check_driver
    of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
AssertionError: 
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

**Thank you very much for your help**

**Comment by GiorgioBarnabo** [comment]
@charlyromero hi :) I have been using your super helpful notebook. Do you know if there is an easy way to process several songs at time? Thank you in advance!
