### ISSUE TITLE
problema de separacion 

### ISSUE THREAD

**Issue by Fulanito0** [facebookresearch/demucs#111]
saludos, adefossez
hermano a pesar de seguir todos los pasos y introducir los comandos que me enviaste, todo sigue igual el problema sigue presente. @adefossez 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jesus/Desktop/demucs/demucs/separate.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

otra cosa hermano, creo que tardas demasiado para responder y ni somos muchos usuarios presentandote problemas que resolver para que tardes dias para contestar.

**Comment by adefossez** [comment]
Did you run `conda activate demucs`?
Otherwise try running the following before the command
```
conda activate demucs
pip install requests
```
then try again the separation command :)
