### ISSUE TITLE
Ya no funciona Demucs

### ISSUE THREAD

**Issue by Diego-Pino** [facebookresearch/demucs#112]
Hi **Community Demucs**.
in past tense I was able to install and run, I made a record and published it in [Personal Website ](https://pinostudio1.com/archive/index.php?thread-2148.html).  

but in present time cannot used Demucs, error always comes out:
- **import tqdm**: _ModuleNotFoundError_: No module named '**tqdm**'
- when try to _install Requirements_, display: pip install tqdm
**Requirement already satisfied** 

and I always stay in that **repetitive cycle of** **library dependencies**.  

to fix i am try to:
- **Update Anaconda** to my system: macOS Sierra (10.12.6)
- **Update version** python: 2.7 to 3.8

Doit **all steps of instalation again**-- in other folder, example: 
**demucs-2** (But the error still displaying).

Another Test:
Try **to downgrade** Adacnonda and Python 2.7 (because was the **version original run in my computer**) but now--- **have two version of Python** and **anaconda with Python 2.7** but the problems still to **run** **Demucs**.

Anexo: imagenes support  --> https://ibb.co/9pyKb2j

![Minion](https://i.ibb.co/BfTWyjR/demucs-error.png)

Code terminal:
```
# To activate this environment, use
#
#     $ conda activate demucs
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) DiegoPino:demucs diegopino$ conda activate demucs
(demucs) DiegoPino:demucs diegopino$ python3 -m demucs.separate --dl -n tasnet /Users/diegopino/Sites/demucs-nuevo/demucs/gordo-c.mp3 -d cpu
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/diegopino/Sites/demucs-nuevo/demucs/demucs/separate.py", line 14, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'
(demucs) DiegoPino:demucs diegopino$ pip install tqdm
Requirement already satisfied: tqdm in /Users/diegopino/opt/anaconda2/envs/demucs/lib/python3.7/site-packages (4.36.1)
(demucs) DiegoPino:demucs diegopino$ 
```

**Any help please**... 

**Thanks in advance for support**!

**Comment by adefossez** [comment]
Hey, can you replace `python3` by `python` and tell me if that works?

**Comment by Diego-Pino** [comment]
Thank You **@adefossez**  now can run Demucs with  `Python`  that was the solution
![Demucs Funciona](https://i.ibb.co/3FQ4T05/demucs-ok.png)

**@adefossez**   Thanks in Advance for Support!

En Resumen: 
- con `Python3` no funciono en mi quipo
- con `Python`  Funciono Perfecto.

Gracias por el Soporte!
