### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by wubinbai** [facebookresearch/demucs#115]
There are 2 cases here. 
================
case 1:

When running:  (As described in the README file, this is for training purpose, where /media/wb/PSSD/datasets/musdb/train/ is the path after I extracted the musdb zip file downloaded officially.(there is also a test/ directory besides)):

python3 -i -m demucs -b 4 --musdb /media/wb/PSSD/datasets/musdb/train/

It prints:

Experiment musdb=train batch_size=4
Number of training samples adjusted to 451924

After ~5 seconds, it prints:

Traceback (most recent call last):
  File "/home/wb/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wb/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wb/git/seperation_music_source_waveform_domain/demucs/demucs/__main__.py", line 266, in <module>
    main()
  File "/home/wb/git/seperation_music_source_waveform_domain/demucs/demucs/__main__.py", line 205, in main
    world_size=args.world_size)
  File "/home/wb/git/seperation_music_source_waveform_domain/demucs/demucs/train.py", line 38, in train_model
    loader = DataLoader(dataset, batch_size=batch_size, num_workers=workers, shuffle=True)
  File "/home/wb/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/wb/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

======================================
case 2:

When running:  (As described in the README file, this is for training purpose, where /media/wb/PSSD/datasets/musdb/train/ is the path after I extracted the musdb zip file downloaded officially.(there is also a test/ directory besides)):

python3 -i -m demucs -b 4 --musdb /media/wb/PSSD/datasets/musdb/train/

It prints:

Experiment musdb=musdb batch_size=4
Number of training samples adjusted to 451924

After ~ 5 seconds, it prints:

Traceback (most recent call last):
  File "/home/wb/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wb/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wb/git/seperation_music_source_waveform_domain/demucs/demucs/__main__.py", line 266, in <module>
    main()
  File "/home/wb/git/seperation_music_source_waveform_domain/demucs/demucs/__main__.py", line 169, in main
    channels=args.audio_channels)
  File "/home/wb/git/seperation_music_source_waveform_domain/demucs/demucs/compressed.py", line 25, in __init__
    meta = dict(metadata[name])
KeyError: 'A Classic Education - NightOwl'

Here is my environment:

Environment OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
Python 3.6.5
with keras, tensorflow, pytorch, and everything else i.e. H/W, S/W installed.

May I @adefossez for support and help?
Thank you!

**Comment by adefossez** [comment]
Can you try passing `/media/wb/PSSD/datasets/musdb/` as a path instead (without the train at the end) ? It should contain two folders: `train` and `test`.

**Comment by wubinbai** [comment]
@adefossez  Thank you for your help~

I tried as what you described, an error pops up.
Here is the command I type:

python3 -i -m demucs -b 4 --musdb /media/wb/PSSD/datasets/musdb/

and the output is around 20 lines of codes:

Experiment musdb=musdb batch_size=4
Number of training samples adjusted to 451924
Traceback (most recent call last):
  File "/home/wb/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wb/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wb/git/seperation_music_source_waveform_domain/demucs/demucs/__main__.py", line 266, in <module>
    main()
  File "/home/wb/git/seperation_music_source_waveform_domain/demucs/demucs/__main__.py", line 169, in main
    channels=args.audio_channels)
  File "/home/wb/git/seperation_music_source_waveform_domain/demucs/demucs/compressed.py", line 25, in __init__
    meta = dict(metadata[name])
KeyError: 'A Classic Education - NightOwl'



================
do you know how to solve this kind of problem? Thanks!

**Comment by Abefocuson** [comment]
Hi I meet the same bug. 

@wubinbai  Did you solve the  problem？ 
@adefossez  We all use the Ubuntu 18.04.1 LTS system.  Is this the reason？

 Thank you for your help.

**Comment by wubinbai** [comment]
@Abefocuson  Hi, I have not solve this problem yet. Let's wait for answers. 

@adefossez  May you help use with some suggestions? Thanks!

**Comment by wubinbai** [comment]
Hi @adefossez Thank you for your help. I tried what you said, both ways, but got the same error.

I tried remove the whole metadata folder, and run again, but same error pops up.

I tried double check that I have the mp4 file as well as other mp4 files in the train directory in my dataset directory... So I think my dataset directory setup is good....

Any other way that I may possibly find what is going on??? and solve, thanks so much!

**Comment by adefossez** [comment]
Sorry I'm not super reactive here. Can you do
```
cat metadata/musdb.json`
```
and give me the output?

**Comment by wubinbai** [comment]
Hi @adefossez  I tried the command, it prints

{}

I checked the json file, it only contains:  {}

nothing else.
thanks, please let me know if you know what's going on, thanks

**Comment by adefossez** [comment]
I checked again from a fresh install and it works for me. Make sure you have the right version of musdb installed (`musdb==0.3.1`), delete the `metadata` folder, make sure you are passing the right pass to musdb and try one last time. If that doesn't work, I'm afraid you would have to do more debugging yourself (if I were you I would add a `print`in `get_musdb_tracks` in `demucs/compressed.py`)

**Comment by weimisa341** [comment]
I must use MUSDB18 Compressed STEMS to train?
if I use MUSDB18hq to train, error shows:
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by weimisa341** [comment]
I already found that if I want musdb.DB work:
1. I need comfirm that    root = "~/musdb/"  ,  the last directory of root must be"musdb"
2. if I want use musdb.DB for musdb18hq, I need use: 
musdb.DB(root, subsets=["train"], split="train", is_wav=True)

**Comment by Abefocuson** [comment]
@weimisa341 

Thanks for your help.

After fix this bug, can you train the model properly?  Is there some problems when extracting samples from audio files?

**Comment by weimisa341** [comment]
> @weimisa341
> 
> Thanks for your help.
> 
> After fix this bug, can you train the model properly? Is there some problems when extracting samples from audio files?

Thanks , I can train the model  properly, everything is ok.

**Comment by weimisa341** [comment]
> @weimisa341
> 
> Thanks for your help.
> 
> After fix this bug, can you train the model properly? Is there some problems when extracting samples from audio files?

but I use musdb18 mp4 to train model, if I use musdbhq, still have some error.

**Comment by adefossez** [comment]
You can't use MUSDB18hq with this codebase. It expected mp4 stems file as input, while musdb18hq is wav.

**Comment by 905058546** [comment]
@wubinbai 
I have the same problem as you on Ubuntu. Have you solved it? KeyError: 'A Classic Education - NightOwl'
How was it solved？It bothered me for a long time

**Comment by yangdaowu** [comment]
> 我已经发现，如果我想要 musdb.DB 工作：
> 
> 1. 我需要确认 root = "~/musdb/" ，root 的最后一个目录必须是"musdb"
> 2. 如果我想将 musdb.DB 用于 musdb18hq，我需要使用：
>    musdb.DB(root, subnets=["train"], split="train", is_wav=True)

**Comment by adefossez** [comment]
> @wubinbai
> I have the same problem as you on Ubuntu. Have you solved it? KeyError: 'A Classic Education - NightOwl'
> How was it solved？It bothered me for a long time

In case you passed the wrong path during a previous run, try to remove all files in the `metadata` folder. Then make sure you pass the root of the musdb directory (it should contain both a `train` and `test` folder). Also please verify if you are using the .wav or .mp4 dataset. If it is the wav dataset (MusdbHQ), then pass `--is_wav` flag.

**Comment by Sourav-Panda** [comment]
I am using the musdb18 compressed. I have no errors but the code dose not proceed further after line number 102. It prints the path and the file names from line 98 but dose not print _build_metadata outside for loop.

an suggestions please.
 
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/95696755/185750795-4f7dd222-59c4-4156-80b6-41dde979dc33.png">

**Comment by adefossez** [comment]
@Sourav-Panda are you using V2 or V3 ? V3 doesn't support the compressed dataset anymore.

**Comment by Sourav-Panda** [comment]
I am using v2
