### ISSUE TITLE
I can't proceed with a MUSDB error

### ISSUE THREAD

**Issue by usasho** [facebookresearch/demucs#120]
i thought about learning using Musdb, but I can't learn due to an error code. What should I do with this?

Code 
Musdb
Traceback (most recent call last):
   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "/home/scss/DeepLearning/VocalEX/sepa/demucs/__main__.py", line 273, in <module>
     main()
   File "/home/scss/DeepLearning/VocalEX/sepa/demucs/__main__.py", line 165, in main
     build_musdb_metadata(args.metadata, args.musdb, args.workers)
   File "/home/scss/DeepLearning/VocalEX/sepa/demucs/compressed.py", line 84, in build_musdb_metadata
     tracks = get_musdb_tracks(musdb)
   File "/home/scss/DeepLearning/VocalEX/sepa/demucs/compressed.py", line 17, in get_musdb_tracks
     return {track.name: track.path for track in mus}
TypeError:'DB' object is not iterable
Task 0 died with exit code 1

**Comment by adefossez** [comment]
What is the version of `musdb` installed? You can check that doing `pip freeze | grep musdb`.
