### ISSUE TITLE
OSError when running demucs under Windows 10

### ISSUE THREAD

**Issue by dev-lang** [facebookresearch/demucs#132]
`python -m demucs.separate --dl -n demucs -d cpu D:\audio.flac
Traceback (most recent call last):
  File "D:\Users\admin\anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Users\admin\anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\demucs\demucs\separate.py", line 13, in <module>
    import torch as th
  File "D:\Users\admin\anaconda3\envs\demucs\lib\site-packages\torch\__init__.py", line 44, in <module>
    import numpy as _np
  File "C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "D:\Users\admin\anaconda3\envs\demucs\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 no es una aplicación Win32 válida`

i am using demucs cpu with **anaconda with python 3.8 64 bits**

what should i do to solve this problem?

**Comment by adefossez** [comment]
It looks like it is using a Python3.7, not 3.8 and it looks like there are two python environments involved, so likely some problem with a PATH env variable.
See: https://github.com/pytorch/pytorch/issues/27693
Make sure to start from a new anaconda shell, try 
```
conda remove --name demucs --all
```
Close the anaconda shell, launch again, and restart the installation procedure.

In case you are setting somewhere any of the env variable $PATH or $PYTHONPATH, remove those to make sure the loading works properly in the anaconda env.
