### ISSUE TITLE
windows10 can't training Demucs on the MusDB

### ISSUE THREAD

**Issue by OJunJie** [facebookresearch/demucs#133]
(demucs) D:\demucs-master\demucs-master>python.exe run.py --musdb "D:\musdb18\train"
Experiment musdb=train
Number of training samples adjusted to 451924
Traceback (most recent call last):
  File "D:\anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\demucs-master\demucs-master\demucs\__main__.py", line 271, in <module>
    main()
  File "D:\demucs-master\demucs-master\demucs\__main__.py", line 210, in main
    world_size=args.world_size)
  File "D:\demucs-master\demucs-master\demucs\train.py", line 38, in train_model
    loader = DataLoader(dataset, batch_size=batch_size, num_workers=workers, shuffle=True)
  File "D:\anaconda3\envs\demucs\lib\site-packages\torch\utils\data\dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "D:\anaconda3\envs\demucs\lib\site-packages\torch\utils\data\sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
Task 0 died with exit code 1

My musdb version==0.3.1

**Comment by adefossez** [comment]
Can you try `python.exe run.py --musdb "D:\musdb18\"` ? musdb18 should contain a train and test folder.

**Comment by OJunJie** [comment]
@adefossez what's musdb.json. (My English is pretty basic)

**Comment by OJunJie** [comment]
> Can you try `python.exe run.py --musdb "D:\musdb18\"` ? musdb18 should contain a train and test folder.

(demucs) D:\demucs-master\demucs-master>python.exe run.py --musdb "D:\musdb18"
Experiment musdb=musdb18
Number of training samples adjusted to 451924
[000] train (1/2):   0%|                                                                    | 0/286 [00:00<?, ? batch/s]Traceback (most recent call last):
  File "D:\anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\demucs-master\demucs-master\demucs\__main__.py", line 271, in <module>
    main()
  File "D:\demucs-master\demucs-master\demucs\__main__.py", line 210, in main
    world_size=args.world_size)
  File "D:\demucs-master\demucs-master\demucs\train.py", line 54, in train_model
    sources = augment(sources)
  File "D:\anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "D:\anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\demucs-master\demucs-master\demucs\augment.py", line 43, in forward
    wav = th.cat([wav.gather(2, left), wav.gather(2, right)], dim=2)
RuntimeError: CUDA out of memory. Tried to allocate 486.00 MiB (GPU 0; 8.00 GiB total capacity; 5.97 GiB already allocated; 425.12 MiB free; 6.07 GiB reserved in total by PyTorch)
                                                                                                                        Task 0 died with exit code 1

what should I do?

**Comment by adefossez** [comment]
You don't have enough memory to train Demucs. You likely need to reduce the model size and capacity, but likely with worse performance, you can try
```
python.exe run.py --musdb "D:\musdb18\" -b 4 --channels 32
```
or even `--channels 24`.
