### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by SheLcat** [facebookresearch/demucs#136]
I get "Solving environment: failed"
When I type "conda env update -f environment-cpu.yml"

I don't know how to solve it.

**Comment by adefossez** [comment]
Hey @SheLcat , what OS are you running?
Could you provide the full output from the command?
Thanks!

**Comment by raraz15** [comment]
I am trying to "conda env update -f environment-cpu.yml" in Windows Subsystem for Linux. And I have been getting:

Preparing transaction: done
Verifying transaction: done
Executing transaction: - By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/oguza97/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/oguza97/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/oguza97/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_update.py", line 126, in execute
        installer.install(prefix, specs, args, env)
      File "/home/oguza97/anaconda3/lib/python3.7/site-packages/conda_env/installers/pip.py", line 36, in _pip_install_via_requirements
        delete=False)
      File "/home/oguza97/anaconda3/lib/python3.7/tempfile.py", line 547, in NamedTemporaryFile
        (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
      File "/home/oguza97/anaconda3/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
        fd = _os.open(file, flags, 0o600)
    PermissionError: [Errno 13] Permission denied: '/home/oguza97/demucs-master/condaenv.1de798yf.requirements.txt'

`$ /home/oguza97/anaconda3/bin/conda-env update -f environment-cpu.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/oguza97/anaconda3/bin/conda
             CONDA_PREFIX=/home/oguza97/anaconda3
    CONDA_PROMPT_MODIFIER=
         CONDA_PYTHON_EXE=/home/oguza97/anaconda3/bin/python
               CONDA_ROOT=/home/oguza97/anaconda3
              CONDA_SHLVL=1
                     PATH=/home/oguza97/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/
                          usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/Wi
                          ndowsApps/CanonicalGroupLimited.UbuntuonWindows_2004.2021.222.0_x64__7
                          9rhkp1fndgsc:/mnt/c/Program Files/NVIDIA GPU Computing
                          Toolkit/CUDA/v11.1/bin:/mnt/c/Program Files/NVIDIA GPU Computing Toolk
                          it/CUDA/v11.1/libnvvp:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WI
                          NDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/m
                          nt/c/WINDOWS/System32/OpenSSH/:/mnt/d/Program
                          Files/MATLAB/R2020b/bin:/mnt/c/Program Files (x86)/NVIDIA
                          Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA
                          Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/NVIDIA
                          Corporation/Nsight Compute 2020.2.0/:/mnt/c/Program Files (x86)/Pulse
                          Secure/VC142.CRT/X64/:/mnt/c/Program Files (x86)/Pulse
                          Secure/VC142.CRT/X86/:/mnt/d/Program Files/Git/cmd:/mnt/c/Users/oguza/
                          AppData/Local/Microsoft/WindowsApps:/snap/bin:/home/oguza97/anaconda3/
                          bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/oguza97/anaconda3
            shell level : 1
       user config file : /home/oguza97/.condarc
 populated config files : /home/oguza97/.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : /home/oguza97/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/oguza97/anaconda3/pkgs
                          /home/oguza97/.conda/pkgs
       envs directories : /home/oguza97/anaconda3/envs
                          /home/oguza97/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/4.4.0-19041-Microsoft ubuntu/20.04 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
