### ISSUE TITLE
trainning problem，how to deal with it

### ISSUE THREAD

**Issue by 905058546** [facebookresearch/demucs#141]
[000] valid:  14%|█████████▌                                                         | 2/14 [00:03<00:21,  1.78s/ track]Traceback (most recent call last):
File "D:\data\xxx\Miniconda\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\data\xxx\Miniconda\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xkw\demucs\demucs\__main__.py", line 271, in <module>
    main()
  File "C:\Users\xkw\demucs\demucs\__main__.py", line 219, in main
    world_size=args.world_size)
  File "C:\Users\xkw\demucs\demucs\train.py", line 103, in validate_model
    estimates = apply_model(model, mix, shifts=shifts, split=split)
  File "C:\Users\xkw\demucs\demucs\utils.py", line 141, in apply_model
    out = model(padded.unsqueeze(0))[0]
  File "D:\data\xxx\Miniconda\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\xkw\demucs\demucs\model.py", line 203, in forward
    x = self.lstm(x)
  File "D:\data\xxx\Miniconda\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\xkw\demucs\demucs\model.py", line 23, in forward
    x = self.lstm(x)[0]
  File "D:\data\xxx\Miniconda\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\data\xxx\Miniconda\envs\demucs\lib\site-packages\torch\nn\modules\rnn.py", line 559, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by adefossez** [comment]
Can you try with the `--split_valid` option ?

**Comment by 905058546** [comment]
> 您可以尝试使用该`--split_valid`选项吗？

Thank you very much ！It worked.
