### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Azeii06** [facebookresearch/demucs#143]
D:\Demucs Install\demucs>py -3.8 -m demucs.separate -d cpu --dl "D:\Demucs Outputs\STIUTK.mp3"
Separated tracks will be stored in D:\Demucs Install\demucs\separated\demucs
File \d does not exist. If the path contains spaces, please try again after surrounding the entire path with quotes "".
Separating track D:\Demucs Outputs\STIUTK.mp3
Traceback (most recent call last):
  File "C:\Users\ebora\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ebora\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Demucs Install\demucs\demucs\separate.py", line 222, in <module>
    main()
  File "D:\Demucs Install\demucs\demucs\separate.py", line 199, in main
    wav = AudioFile(track).read(streams=0, samplerate=44100, channels=2).to(args.device)
  File "D:\Demucs Install\demucs\demucs\audio.py", line 98, in read
    streams = np.array(range(len(self)))[streams]
  File "D:\Demucs Install\demucs\demucs\audio.py", line 59, in __len__
    return len(self._audio_streams)
  File "D:\Demucs Install\demucs\demucs\audio.py", line 54, in _audio_streams
    index for index, stream in enumerate(self.info["streams"])
  File "D:\Demucs Install\demucs\demucs\audio.py", line 44, in info
    self._info = _read_info(self.path)
  File "D:\Demucs Install\demucs\demucs\audio.py", line 17, in _read_info
    stdout_data = sp.check_output([
  File "C:\Users\ebora\anaconda3\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\ebora\anaconda3\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\ebora\anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ebora\anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by adefossez** [comment]
Are you using conda ? It seems `ffmpeg` is not available on your system.

**Comment by Azeii06** [comment]
I appreciate the response, but I actually reinstalling conda(switching to
miniconda from anaconda3 cuz it's too large) I'll let you know if I
stumble some problems again..
Thank you.

**Comment by Azeii06** [comment]
After reinstalling everything from a scratch and reassured that I installed **ffmpeg** this error comes next...

PS D:\Demucs Install\demucs> python.exe -m demucs.separate -d cpu --dl STIUTK.mp3
Separated tracks will be stored in D:\Demucs Install\demucs\separated\demucs
Separating track STIUTK.mp3
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Demucs Install\demucs\demucs\separate.py", line 222, in <module>
    main()
  File "D:\Demucs Install\demucs\demucs\separate.py", line 199, in main
    wav = AudioFile(track).read(streams=0, samplerate=44100, channels=2).to(args.device)
  File "D:\Demucs Install\demucs\demucs\audio.py", line 126, in read
    sp.run(command, check=True)
  File "C:\ProgramData\Miniconda3\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-loglevel', 'panic', '-i', 'STIUTK.mp3', '-map', '0:0', '-threads', '1', '-f', 'f32le', '-ar', '44100', 'C:\\Users\\ebora\\AppData\\Local\\Temp\\tmpyrrux1q1']' returned non-zero exit status 1.

**Comment by adefossez** [comment]
Can you run
```
ffmpeg -i STIUTK.mp3 tmp.wav
```
And see if it works? It should output a file tmp.wav with the same audio os your mp3 file.
