### ISSUE TITLE
Errors Running in Windows

### ISSUE THREAD

**Issue by jtroglia2020** [facebookresearch/demucs#147]
Hi, i am running in Windows, when i run the comands in the console show errors:
![image](https://user-images.githubusercontent.com/75629981/101644195-ab708600-3a13-11eb-8a4a-c932c68eee7d.png)
_Traceback (most recent call last):
  File "C:\Users\Troglia\Anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Troglia\Anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Troglia\demucs\demucs\separate.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'_

**Comment by jtroglia2020** [comment]
when run the comands again, download some stuffs and it work well.
