### ISSUE TITLE
GPUs are not used

### ISSUE THREAD

**Issue by katie-cathy-hunt** [facebookresearch/demucs#148]
Here is the output of `nvidia-smi`:
![image](https://user-images.githubusercontent.com/57769557/102150323-275c3b00-3e25-11eb-9aed-4f1249ed7c72.png)

The content of `environment-cuda.yml` which is from the `master` branch as of December 14, 2020 is
```
name: demucs

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.7
  - cudatoolkit=10
  - ffmpeg==4.2
  - pytorch=1.4.0
  - scipy==1.3.1
  - tqdm==4.36.1
  - pip
  - pip:
    - lameenc==1.2.2
    - musdb==0.3.1
    - museval==0.3.0
    - requests==2.22
    - treetable==0.2.3
```

I ran  the following:
```
conda env update -f environment-cuda.yml
conda activate demucs
python3 -m demucs.separate --dl -n demucs_extra '/path/to/audio.mp3'
```

Installation was successful and the model was downloaded, however I got the following error when running the `separate` script:
```
Separated tracks will be stored in /home/katie/project/code/conda_envs/demucs/demucs/separated/demucs_extra
Separating track /home/katie/project/audio_files/audio.mp3
  0%|                                                                                      | 0/190 [00:00<?, ?seconds/s]Traceback (most recent call last):
  File "/home/katie/anaconda3/envs/demucs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/katie/anaconda3/envs/demucs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/katie/project/code/conda_envs/demucs/demucs/demucs/separate.py", line 239, in <module>
    main()
  File "/home/katie/project/code/conda_envs/demucs/demucs/demucs/separate.py", line 221, in main
    sources = apply_model(model, wav, shifts=args.shifts, split=args.split, progress=True)
  File "/home/katie/project/code/conda_envs/demucs/demucs/demucs/utils.py", line 120, in apply_model
    chunk_out = apply_model(model, chunk, shifts=shifts)
  File "/home/katie/project/code/conda_envs/demucs/demucs/demucs/utils.py", line 141, in apply_model
    out = model(padded.unsqueeze(0))[0]
  File "/home/katie/anaconda3/envs/demucs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/katie/project/code/conda_envs/demucs/demucs/demucs/model.py", line 198, in forward
    x = encode(x)
  File "/home/katie/anaconda3/envs/demucs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/katie/anaconda3/envs/demucs/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/katie/anaconda3/envs/demucs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/katie/anaconda3/envs/demucs/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 202, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
  0%|                                                                                      | 0/190 [00:00<?, ?seconds/s]
```

My driver is compatible with the CUDA toolkit according to Nvidia's doc:
![image](https://user-images.githubusercontent.com/57769557/102171161-c34c6d80-3e4a-11eb-83f0-d0c3429aa999.png)

I updated `environment-cuda.yml` with the following line change to see if it works:
```
  - cudatoolkit=11
```

I ran  the following again:
```
conda env update -f environment-cuda.yml
conda activate demucs
python3 -m demucs.separate --dl -n demucs_extra '/path/to/audio.mp3'
```
and it ran successfully in that it created all the separation audio files however I noticed that it did not use the GPUs. 

I confirmed that by adding the following print statement to the main function of `separate.py`:
```
print(th.cuda.is_available())
```
and it returned "False".

I have no idea how to debug this further.

Any idea how to make sure that `separate.py` uses the GPUs?

Any pointers are appreciated!

**Comment by katie-cathy-hunt** [comment]
Nvm.

I figured it out:
![image](https://user-images.githubusercontent.com/57769557/102173779-b3d02300-3e50-11eb-8e51-3a1b1a3fd60f.png)

Pytorch 1.7.x works well with my driver version i.e. 455.45.01.
