### ISSUE TITLE
Strange error code 

### ISSUE THREAD

**Issue by imRig** [facebookresearch/demucs#15]
After I entered the separate command and it reached to 27%, a whole lot of text saying that there was an error appeared.

I've gotta say that I've never used python or used a code program in my life:

Traceback (most recent call last):
  File "C:\Users\usuario\Anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\usuario\Anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usuario\demucs\demucs\separate.py", line 143, in <module>
    main()
  File "C:\Users\usuario\demucs\demucs\separate.py", line 121, in main
    download_file(url, model_path, sha256)
  File "C:\Users\usuario\demucs\demucs\separate.py", line 59, in download_file
    _download()
  File "C:\Users\usuario\demucs\demucs\separate.py", line 56, in _download
    "Expected {} but got {}".format(url, sha256, signature))
ValueError: Invalid sha256 signature when downloading https://dl.fbaipublicfiles.com/demucs/demucs.th. Expected b25b32a4772e43983d2e30cce17a85aaa1baf3aea0a6145eb591b0f393ac9312 but got 9e95ed43031d52296308db46761c539530101709eeca6e2fca3e1e804fdfdabd

Also I'm on Windows 10.

If somebody could help me I would be really happy :D

**Comment by imRig** [comment]
Somehow, It got fixed. Nevermind.
