### ISSUE TITLE
Failed to load the model for inference

### ISSUE THREAD

**Issue by 121898** [facebookresearch/demucs#158]
Hi,
       Thanks for this implementation, I met a problem when using this repo.
       First, it seems I can successfully train the model by myself, using the default setups (120 epochs), after the training, the model is also generated in the models/ directory. However, when I want to load it for separation, a failure happens as follows,

```bash
python -m demucs.separate -n raw\=rawdata\ musdb\=musdb18\ batch_size\=8 --models exp/models/ -d cuda  mixture.mp3

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/workspace/ass/demucs/demucs/separate.py", line 228, in <module>
    main()
  File "/home/user/workspace/ass/demucs/demucs/separate.py", line 190, in main
    model = load_model(model_path).to(args.device)
  File "/home/user/workspace/ass/demucs/demucs/utils.py", line 164, in load_model
    klass, args, kwargs, state = th.load(load_from, 'cpu')
  File "/home/user/tools/py3/lib64/python3.6/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/user/tools/py3/lib64/python3.6/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/home/user/tools/py3/lib64/python3.6/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/user/tools/py3/lib64/python3.6/site-packages/torch/serialization.py", line 833, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading file data/3054887184: invalid header or archive is corrupted
```

The name `exp/models/raw=rawdata musdb=musdb18 batch_size=8.th` is generated by default. I also tried to download your pretrained model, and everything just works fine. Have any ideas about this?

Thanks.

**Comment by adefossez** [comment]
I think the file did not get written properly. But you can regenerate the final model by launching again the training with the `--save_model` parameter. It will use the checkpoint in `checkpoints/`, skip training and go straight to saving the trained model. You must still have the checkpoint in `checkpoints/` around for that to work.

**Comment by 121898** [comment]
> I think the file did not get written properly. But you can regenerate the final model by launching again the training with the `--save_model` parameter. It will use the checkpoint in `checkpoints/`, skip training and go straight to saving the trained model. You must still have the checkpoint in `checkpoints/` around for that to work.

Thanks for the suggestion and it works now. I will close this issue.

**Comment by 121898** [comment]
Using --save_model to regenerate the model from checkpoint can fix this issue.
