### ISSUE TITLE
URGENT Basic Help Needed in Transfer Learning and Fine Tuning

### ISSUE THREAD

**Issue by jaslineljy** [facebookresearch/demucs#161]
Hi i am new to AI and have little knowledge regarding coding. I came across this open-source project and found it interesting and would like to conduct experiments with this model as part of my assignment. However, there are some stuff that i am confused about and would like your advice and help.

From what i have googled, i understand that there is something called transfer learning and i could use the model to and test it on another dataset. (Not sure if having more training dataset is considered as transfer learning or is just called further training?) 

I also understand that fine tuning is an approach for transfer learning. One of the ways to do fine tuning is to freeze layers.
**My question is** 
**1) how do i go about to code and freeze the layers. And how to choose how many layers to freeze
2) why does fine tuning take place in last few layers?
3) After freezing, if i change the hyperparams and add regulation methods is it considered as finetuning? Or what features to change is considered as finetuning?**

Currently, I have made the model smaller and named it as main_.py instead of the original file name (cause i don't want to lose the original and is easy to refer) as i am running on 1 GPU. After the training process, i have my model saved as `demucs_small.th under demucs/models folder` . I manage to run the `main_.py --test musdb=musdb18_stem.th` and obtained the metrics for each individual SDR of each song in the .json.gz format. 

**However, how do i go about finding the metric for the model itself?** I tried running the following code but all i got was the paper metrics not from the `demucs_small.th`
>>python3 valid_table.py # shows the best validation loss for all trained models
python3 result_table.py # shows the SDR for all trained models
python3 result_table.py SIR # shows the SIR for all trained models

I changed my path in line 23 in result_table.py from Path("evals") to Path("demucs/evals") But i got the following error
>>Traceback (most recent call last):
  File "result_table.py", line 83, in <module>
    parts = [(k, v) for k, v in parts if k != STD_KEY]
  File "result_table.py", line 83, in <listcomp>
    parts = [(k, v) for k, v in parts if k != STD_KEY]
ValueError: too many values to unpack (expected 2)

I unpacked it but it does not show the `demucs_small.th` metrics but the baseline metrics only as shown below.
![image](https://user-images.githubusercontent.com/44189034/108698465-20495b80-753f-11eb-80d8-32e7d1f28c2f.png)

I understand that i `run.py` allow us to test a model that we downloaded but I am not sure what does it output. When i tried running, i also got the following error:
>>Traceback (most recent call last):
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fyp/FYP/demucs/__main__.py", line 18, in <module>
    from .compressed import StemsSet, build_musdb_metadata, get_musdb_tracks
  File "/home/fyp/FYP/demucs/compressed.py", line 12, in <module>
    from audio import AudioFile
ModuleNotFoundError: No module named 'audio'
Traceback (most recent call last):
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fyp/FYP/demucs/__main__.py", line 18, in <module>
    from .compressed import StemsSet, build_musdb_metadata, get_musdb_tracks
  File "/home/fyp/FYP/demucs/compressed.py", line 12, in <module>
    from audio import AudioFile
ModuleNotFoundError: No module named 'audio'
Traceback (most recent call last):
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fyp/FYP/demucs/__main__.py", line 18, in <module>
    from .compressed import StemsSet, build_musdb_metadata, get_musdb_tracks
  File "/home/fyp/FYP/demucs/compressed.py", line 12, in <module>
    from audio import AudioFile
ModuleNotFoundError: No module named 'audio'
Traceback (most recent call last):
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fyp/FYP/demucs/__main__.py", line 18, in <module>
    from .compressed import StemsSet, build_musdb_metadata, get_musdb_tracks
  File "/home/fyp/FYP/demucs/compressed.py", line 12, in <module>
    from audio import AudioFile
ModuleNotFoundError: No module named 'audio'
Traceback (most recent call last):
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fyp/FYP/demucs/__main__.py", line 18, in <module>
    from .compressed import StemsSet, build_musdb_metadata, get_musdb_tracks
  File "/home/fyp/FYP/demucs/compressed.py", line 12, in <module>
    from audio import AudioFile
ModuleNotFoundError: No module named 'audio'
Traceback (most recent call last):
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fyp/FYP/demucs/__main__.py", line 18, in <module>
    from .compressed import StemsSet, build_musdb_metadata, get_musdb_tracks
  File "/home/fyp/FYP/demucs/compressed.py", line 12, in <module>
    from audio import AudioFile
ModuleNotFoundError: No module named 'audio'
Traceback (most recent call last):
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fyp/FYP/demucs/__main__.py", line 18, in <module>
    from .compressed import StemsSet, build_musdb_metadata, get_musdb_tracks
  File "/home/fyp/FYP/demucs/compressed.py", line 12, in <module>
    from audio import AudioFile
ModuleNotFoundError: No module named 'audio'
Traceback (most recent call last):
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fyp/.conda/envs/demucs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fyp/FYP/demucs/__main__.py", line 18, in <module>
    from .compressed import StemsSet, build_musdb_metadata, get_musdb_tracks
  File "/home/fyp/FYP/demucs/compressed.py", line 12, in <module>
    from audio import AudioFile
ModuleNotFoundError: No module named 'audio'
Task 0 died with exit code 1
Task 2 died with exit code 1
Task 4 died with exit code 1
Task 6 died with exit code 1 
 
**Also, what should i type to separate my own audio file with this new model i have saved so that i can hear what it is like and compare with the model's SDR**  (`=musdb18_stem.th`) since i don't think i could use what is originally given. 
` python3 -m demucs.separate --dl -n demucs PATH_TO_AUDIO_FILE_1 [PATH_TO_AUDIO_FILE_2 ...] ` 

Sorry for the very long question and hope that someone can help solve my doubts soon since the duration for the assignment is short. Thank you very much.

**Comment by adefossez** [comment]
For evaluating a model that is trained, can you list the content of `demucs/evals` ? why of the filename must be ill formated, the script excepts the paths to be of the form `something=value something_else=other_value` etc.

The `from  audio import AudioFile` line should be `from .audio import AudioFile` as it is in master. To run the custom script you have you need to do `python -m demucs.main_` with `main_` the same of the new script without `.py`.

As for the questions on fine tuning, I have never tried to fine tune a Demucs model, but you cannot infer that what is true for vision and image classification will be true here too. As a first try I would try to let all the parameters move freely, but that is likely going to quickly end up in forgetting the initial point.

**Comment by jaslineljy** [comment]
For the evaluation, my file name is in the form of `something=value`
![image](https://user-images.githubusercontent.com/44189034/108892426-d0f05180-764a-11eb-94f1-88ba35e5c3a9.png)

however, i am unable to get the metric for this new model after running 
`python3 valid_table.py # shows the best validation loss for all trained models`
`python3 result_table.py # shows the SDR for all trained models`
`python3 result_table.py SIR # shows the SIR for all trained models`

I am not sure if i was suppose to type metric (`python3 result_table.py metric`)
but i got an error as follows
>>Traceback (most recent call last):
  File "result_table.py", line 66, in <module>
    all_stats[name] = [read(args.metric, BASELINE_EVALS / name / "test")]
  File "result_table.py", line 58, in read
    metrics = read_track(metric, results, pool=pool)
  File "result_table.py", line 47, in read_track
    metrics = [frame["metrics"][metric] for frame in target["frames"]]
  File "result_table.py", line 47, in <listcomp>
    metrics = [frame["metrics"][metric] for frame in target["frames"]]
KeyError: 'metric'

**Comment by adefossez** [comment]
for the valid table and resulttable, don't provide anything but
`python valid_table.py` and report the error you get. check that the training has completed properly (there should be a file `logs/MODEL_NAME.done`).

use `-n musdb=musdb18_stem`, check that the file exist in `models/`, don't use `--dl`, this is for pre-trained

The `no module named 'model'` is probably because you changed around imports before training (same as `audio` import before), that you will have to restore to the way it is in the repo.

`list(model.parameters())[-10:]` will get you the last 10 layers for instance, there is no reason this makes any sense.

you can't test 3 sources unless you understand the code better and hack it yourself. you will have to figure it out on your own.

**Comment by jaslineljy** [comment]
Hi @adefossez i manage to finally get the Metrics for my model from result_table, though the valid_table is still empty. 

I have restored to the way it is in the repo but i still get the same error `no module named 'model'`. Can I check whether does `state_dict` in the `__main__.py` have any impact on this?

**Comment by jaslineljy** [comment]
Manage to solve it thank you for your time :)

**Comment by Sourav-Panda** [comment]
@jaslineljy could you do transfer learning? I need to know I am in urgent need thanks.
