### ISSUE TITLE
hi have problem, File "C:\Users\berna\anaconda3\envs\demucs\lib\site-packages\torch\__init__.py", line 81, in <module>  from torch._C import * ImportError: DLL load failed: El sistema operativo no puede ejecutar %1.

### ISSUE THREAD

**Issue by tiagobernal** [facebookresearch/demucs#166]
(demucs) C:\Users\berna\anaconda3\demucs\demucs-master>python.exe -m demucs.separate --dl C:\Users\berna\anaconda3\demucs\Origen.mp3
Traceback (most recent call last):
  File "C:\Users\berna\anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\berna\anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\berna\anaconda3\demucs\demucs-master\demucs\separate.py", line 13, in <module>
    import torch as th
  File "C:\Users\berna\anaconda3\envs\demucs\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: El sistema operativo no puede ejecutar %1.

(demucs) C:\Users\berna\anaconda3\demucs\demucs-master>

thanks

👍 

Santiago

**Comment by tiagobernal** [comment]
i have win 10 64 bits msi h370 board processor intel i7 8700

run both cpu ang gpu and same problem

im install anaconda 2020.2 with pytom 3.7
and install acaconda 2021 with pytom 3.8

same problem

im update conda 
jesus seco video

but have the same problem

im change carpets external internal anaconda carpet install demucs 

but nothing

please help

thanks

**Comment by walterjose4** [comment]
I have the same problem :/
(demucs) PS C:\Users\pc> cd d:\demucs
(demucs) PS D:\demucs> conda activate demucs
(demucs) PS D:\demucs> python.exe -m demucs.separate -d cuda --dl "D:\Audios\ready_to_start.mp3"
Traceback (most recent call last):
  File "C:\Users\pc\.conda\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\pc\.conda\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\demucs\demucs\separate.py", line 13, in <module>
    import torch as th
  File "C:\Users\pc\.conda\envs\demucs\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: The operating system cannot run %1.

**Comment by walterjose4** [comment]
Run Anaconda powershell prompt as administrator

conda activate demucs

cd demucs

conda uptade --all

conda update -n base -c defaults conda
