### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the specified file

### ISSUE THREAD

**Issue by ghost** [facebookresearch/demucs#17]
Ok so I did everything perfect but it reached 100% and then this appeared. 

```
(base) C:\Users\name\Downloads\demucs-master>python.exe -m demucs.separate --dl -n demucs C:\Users\name\Desktop\song.mp3
100%|█████████████████████████████████████████████████████████████████████████████| 2.59G/2.59G [03:59<00:00, 10.8MB/s]
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\name\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\name\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\name\Downloads\demucs-master\demucs\separate.py", line 143, in <module>
    main()
  File "C:\Users\name\Downloads\demucs-master\demucs\separate.py", line 127, in main
    wav = AudioFile(track).read(streams=0, samplerate=44100, channels=2).to(args.device)
  File "C:\Users\name\Downloads\demucs-master\demucs\audio.py", line 97, in read
    streams = np.array(range(len(self)))[streams]
  File "C:\Users\name\Downloads\demucs-master\demucs\audio.py", line 58, in __len__
    return len(self._audio_streams)
  File "C:\Users\name\Downloads\demucs-master\demucs\audio.py", line 53, in _audio_streams
    index for index, stream in enumerate(self.info["streams"])
  File "C:\Users\name\Downloads\demucs-master\demucs\audio.py", line 43, in info
    self._info = _read_info(self.path)
  File "C:\Users\name\Downloads\demucs-master\demucs\audio.py", line 18, in _read_info
    ['ffprobe', str(path), '-print_format', 'json', '-show_format', '-show_streams']
  File "C:\Users\name\Anaconda3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Users\name\Anaconda3\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\name\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\name\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
```

And now everytime that I try to do it doesn't even load, it loads 0% and then that error appears every time

```
(base) C:\Users\name\Downloads\demucs-master\demucs-master>python.exe -m demucs.separate --dl -n demucs C:\Users\name\Desktop\song.mp3
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\name\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\name\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\name\Downloads\demucs-master\demucs-master\demucs\separate.py", line 143, in <module>
    main()
  File "C:\Users\name\Downloads\demucs-master\demucs-master\demucs\separate.py", line 127, in main
    wav = AudioFile(track).read(streams=0, samplerate=44100, channels=2).to(args.device)
  File "C:\Users\name\Downloads\demucs-master\demucs-master\demucs\audio.py", line 97, in read
    streams = np.array(range(len(self)))[streams]
  File "C:\Users\name\Downloads\demucs-master\demucs-master\demucs\audio.py", line 58, in __len__
    return len(self._audio_streams)
  File "C:\Users\name\Downloads\demucs-master\demucs-master\demucs\audio.py", line 53, in _audio_streams
    index for index, stream in enumerate(self.info["streams"])
  File "C:\Users\name\Downloads\demucs-master\demucs-master\demucs\audio.py", line 43, in info
    self._info = _read_info(self.path)
  File "C:\Users\name\Downloads\demucs-master\demucs-master\demucs\audio.py", line 18, in _read_info
    ['ffprobe', str(path), '-print_format', 'json', '-show_format', '-show_streams']
  File "C:\Users\name\Anaconda3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Users\name\Anaconda3\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\name\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\name\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

**Comment by DaZ829** [comment]
Same error using Windows 10

**Comment by beruth35** [comment]
Same error, windows 10

**Comment by adefossez** [comment]
Hey guys, and sorry for my late reply.
The first download bar is only for downloading the pre-trained model. Are you sure the file `C:\Users\name\Desktop\song.mp3` exist? It seems it cannot load it. Can you try running from the Anaconda prompt `ffprobe C:\Users\name\Desktop\song.mp3` ?

**Comment by adefossez** [comment]
Closing for now, please re-open if you still have a problem.

**Comment by AlvaroBeiro** [comment]
I had the exact same problem and it was before I run this command:

```
conda env update -f environment-cpu.yml # if you don't have GPUs
conda env update -f environment-cuda.yml # if you have GPUs
conda activate demucs
```
Because the Windows guide is after that, I went for the Windows guide first.
