### ISSUE TITLE
v2 - "name 'C' is not defined" when using Tasnet

### ISSUE THREAD

**Issue by JeffreyCA** [facebookresearch/demucs#180]
## 🐛 Bug Report

I'm unable to perform separation using Tasnet model with Demucs v2.

## To Reproduce

1. `pip install demucs`
2. `python -m demucs.separate -d cpu -n tasnet file.mp3`

## Expected behavior

Should perform source separation using Tasnet.

## Actual Behavior

```
Traceback (most recent call last):
  File "/Users/jeffrey/.pyenv/versions/3.7.9/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/jeffrey/.pyenv/versions/3.7.9/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jeffrey/.pyenv/versions/3.7.9/Python.framework/Versions/3.7/lib/python3.7/site-packages/demucs/separate.py", line 185, in <module>
    main()
  File "/Users/jeffrey/.pyenv/versions/3.7.9/Python.framework/Versions/3.7/lib/python3.7/site-packages/demucs/separate.py", line 140, in main
    model = load_pretrained(args.name)
  File "/Users/jeffrey/.pyenv/versions/3.7.9/Python.framework/Versions/3.7/lib/python3.7/site-packages/demucs/pretrained.py", line 54, in load_pretrained
    return tasnet(pretrained=True)
  File "/Users/jeffrey/.pyenv/versions/3.7.9/Python.framework/Versions/3.7/lib/python3.7/site-packages/demucs/pretrained.py", line 101, in tasnet
    model = ConvTasNet(X=10, sources=SOURCES)
  File "/Users/jeffrey/.pyenv/versions/3.7.9/Python.framework/Versions/3.7/lib/python3.7/site-packages/demucs/utils.py", line 321, in __init__
    init(self, *args, **kwargs)
  File "/Users/jeffrey/.pyenv/versions/3.7.9/Python.framework/Versions/3.7/lib/python3.7/site-packages/demucs/tasnet.py", line 111, in __init__
    self.separator = TemporalConvNet(N, B, H, P, X, R, C, norm_type, causal, mask_nonlinear)
NameError: name 'C' is not defined
```

## Your Environment

- Python and PyTorch version: 3.7.9
- Operating system and version (desktop or mobile): macOS 11.4
- Hardware (gpu or cpu, amount of RAM etc.): CPU, 16 GB RAM

**Comment by JeffreyCA** [comment]
It looks like the fix was made in https://github.com/facebookresearch/demucs/commit/3e5910cb920984bbddb8391934bce4c8764c7de1, but a release containing the fix hasn't been published?

**Comment by adefossez** [comment]
That is correct, let me update a new version to PyPI

**Comment by adefossez** [comment]
and it should be good now :)

**Comment by JeffreyCA** [comment]
Thanks, all good now!
