### ISSUE TITLE
🐛  Bug Report: Initializing Demucs Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by DeveloperID14** [facebookresearch/demucs#199]
## 🐛 Bug Report: Initializing Demucs Ubuntu 18.04.5 LTS

When I run demucs on my server Ubuntu 18.04.5 LTS and I initialize demucs with the following commands:

```
conda activate
conda env update -f environment-cpu.yml
cd demucs
conda activate demucs
python3 -m demucs.separate -d cpu /root/sexycool.mp3
```

Then the terminal give the following errors:

```

Traceback (most recent call last):
  File "/root/anaconda3/envs/demucs/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/demucs/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/demucs/demucs/separate.py", line 14, in <module>
    import torchaudio as ta
  File "/root/anaconda3/envs/demucs/lib/python3.8/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import extension  # noqa: F401
  File "/root/anaconda3/envs/demucs/lib/python3.8/site-packages/torchaudio/extension/__init__.py", line 5, in <module>
    _init_extension()
  File "/root/anaconda3/envs/demucs/lib/python3.8/site-packages/torchaudio/extension/extension.py", line 11, in _init_extension
    _init_script_module(ext)
  File "/root/anaconda3/envs/demucs/lib/python3.8/site-packages/torchaudio/extension/extension.py", line 19, in _init_script_module
    torch.classes.load_library(path)
  File "/root/anaconda3/envs/demucs/lib/python3.8/site-packages/torch/_classes.py", line 46, in load_library
    torch.ops.load_library(path)
  File "/root/anaconda3/envs/demucs/lib/python3.8/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/root/anaconda3/envs/demucs/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /root/anaconda3/envs/demucs/lib/python3.8/site-packages/torchaudio/_torchaudio.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
```

**Comment by KimberleyJensen** [comment]
@DeveloperID14 I had this problem to i fixed it by switching conda-forge and pytorch in the environment-cuda.yml file 

were it says 

channels:
  - conda-forge
  - pytorch

switch it so pytorch is on top and conda-forge is under it

channels:
  - pytorch
  - conda-forge
  
i kept everything the same and installed everything again from the start and it worked. you will have to edit the environment-cpu.yml file since you are using cpu, i hope this helps !!

**Comment by adefossez** [comment]
@KimberleyJensen  thanks a lot for sharing your solution. I have changed the order in the files so this should fix the issue for all.

**Comment by adefossez** [comment]
I will close this issue, feel free to comment if @KimberleyJensen  solution did not work for you.
