### ISSUE TITLE
Training and evaluating a vocal model only

### ISSUE THREAD

**Issue by Anjok07** [facebookresearch/demucs#221]
## ❓ Questions

I'd love to train a model from scratch using our own dataset. It's already formatted appropriately and we've already trained an incredibly strong onnx vocal model using KUIELAB-MDX-Net code. 

Is it possible to train an individual stem model in Demucs V3?

**Comment by adefossez** [comment]
So it is possible, but with a bit of hacking.
Comment the following line so that the musdb dataset is not loaded:
https://github.com/facebookresearch/demucs/blob/main/demucs/train.py#L80

Create a folder with `train` and `valid` subfolders and in each put one folder per track, with three files: `vocals.wav`, `non_vocals.wav`, `mixture.wav`.

Then create a file in `conf/dset/my_dset.yaml` and change the paths (like https://github.com/facebookresearch/demucs/blob/main/conf/dset/extra44.yaml),
and add a line to have something like:
```
dset:
  wav: ...
  ...
  sources: ['vocals', 'non_vocals']
```

You might want to deactivate this `if` statement to skip evaluation on musdb: `https://github.com/facebookresearch/demucs/blob/main/demucs/solver.py#L266`

Then finally, you can run an experiment with `dora run -d dset=my_dset`.

**Comment by Anjok07** [comment]
Thanks! I got hit with this error though - 

`C:\Users\Anjok\Desktop\demucs-main>dora run -d dset=my_dset
Executor: Starting 1 worker processes for DDP.
[11-15 02:43:06][demucs.train][INFO] - For logs, checkpoints and samples check C:\Users\Anjok\Desktop\demucs-main\outputs\xps\d23a69c5
[11-15 02:43:06][dora.distrib][INFO] - world_size is 1, skipping init.
[11-15 02:43:08][demucs.train][INFO] - train/valid set size: 243576 20
[11-15 02:43:08][demucs.solver][INFO] - ----------------------------------------------------------------------
[11-15 02:43:08][demucs.solver][INFO] - Training...
Error executing job with overrides: ['dset=my_dset']
Traceback (most recent call last):
  File "C:\Users\Anjok\Desktop\demucs-main\demucs\train.py", line 149, in main
    solver.train()
  File "C:\Users\Anjok\Desktop\demucs-main\demucs\solver.py", line 195, in train
    metrics['train'] = self._run_one_epoch(epoch)
  File "C:\Users\Anjok\Desktop\demucs-main\demucs\solver.py", line 305, in _run_one_epoch
    for idx, sources in enumerate(logprog):
  File "c:\users\anjok\anaconda3\lib\site-packages\dora\log.py", line 64, in __next__
    value = next(self._iterator)
  File "c:\users\anjok\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "c:\users\anjok\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "c:\users\anjok\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "c:\users\anjok\anaconda3\lib\site-packages\torch\_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "c:\users\anjok\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "c:\users\anjok\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "c:\users\anjok\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Anjok\Desktop\demucs-main\demucs\repitch.py", line 47, in __getitem__
    stream = repitch(
  File "C:\Users\Anjok\Desktop\demucs-main\demucs\repitch.py", line 68, in repitch
    save_audio(wav, infile.name, samplerate, clip='clamp')
  File "C:\Users\Anjok\Desktop\demucs-main\demucs\audio.py", line 247, in save_audio
    ta.save(str(path), wav, sample_rate=samplerate)
  File "c:\users\anjok\anaconda3\lib\site-packages\torchaudio\backend\soundfile_backend.py", line 429, in save
    soundfile.write(
  File "c:\users\anjok\anaconda3\lib\site-packages\soundfile.py", line 314, in write
    with SoundFile(file, 'w', samplerate, channels,
  File "c:\users\anjok\anaconda3\lib\site-packages\soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "c:\users\anjok\anaconda3\lib\site-packages\soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "c:\users\anjok\anaconda3\lib\site-packages\soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'C:\\Users\\Anjok\\AppData\\Local\\Temp\\tmpcpep41rh.wav': System error.`

**Comment by Anjok07** [comment]
Thank you! I got it running now! I'll let you know if I run into any issues 😀👍

**Comment by R7788380** [comment]
> Thank you! I got it running now! I'll let you know if I run into any issues 😀👍

Thank you for your issue.
I'd like to train from scratch. Could you provide your `my_dest.yaml` example ?

**Comment by K3nn3th2** [comment]
> Thank you! I got it running now! I'll let you know if I run into any issues grinning+1

Hey @Anjok07, did you manage to make your model more robust?

**Comment by CarlGao4** [comment]
@K3nn3th2 It won't get good results since the dataset is created by another program which can separate musics. I think the ideal dataset is recording your own songs with separated channels. If you can get datasets like this, it will be much better.

**Comment by johndpope** [comment]
Sorry - I'm stuck on commenting out line 80

    # train_set, valid_set = get_musdb_wav_datasets(args.dset)
this defines the train_set / valid_set varaibles which are used in subsequent lines.
Are you saying these variables should be set to null ?  or ..???

I'm looking to use 5 stems - all of the dset parameters in conf are set to 2 channels. 

I mentioned this in the other ticket referenced above - but I’ve been using spleeter for years and the  training config is very straightforward - some sample config files 

https://github.com/deezer/spleeter/blob/master/configs/musdb_config.json

just point to a training csv
https://github.com/deezer/spleeter/blob/master/configs/musdb_train.csv

And corresponding validation csv
https://github.com/deezer/spleeter/blob/master/configs/musdb_validation.csv

gonna have to revert back to spleeter instead. 
Please provide simple custom training examples in the repo which don't require hacks.

**Comment by dustyny** [comment]
I looks like this function needs to be replaced with a generalized one?

https://github.com/facebookresearch/demucs/blob/5b20114b1b235ffdb7a5999133a47d429fb0bd03/demucs/wav.py#L212

**Comment by mr-segfault** [comment]
> So it is possible, but with a bit of hacking. Comment the following line so that the musdb dataset is not loaded: https://github.com/facebookresearch/demucs/blob/main/demucs/train.py#L80
> 

I can generate my own songs (full instrumentals, N-numbers of channels) rather quickly, if I had more than two types of stems, would I modify this:
  sources: ['vocals', 'non_vocals'] to be something similar to sources: ['vocals', 'guitar', 'piano', 'flute', 'drum', 'bass'] etc?

**Comment by Anjok07** [comment]
> So it is possible, but with a bit of hacking. Comment the following line so that the musdb dataset is not loaded: https://github.com/facebookresearch/demucs/blob/main/demucs/train.py#L80
> 
> Create a folder with `train` and `valid` subfolders and in each put one folder per track, with three files: `vocals.wav`, `non_vocals.wav`, `mixture.wav`.
> 
> Then create a file in `conf/dset/my_dset.yaml` and change the paths (like https://github.com/facebookresearch/demucs/blob/main/conf/dset/extra44.yaml), and add a line to have something like:
> 
> ```
> dset:
>   wav: ...
>   ...
>   sources: ['vocals', 'non_vocals']
> ```
> 
> You might want to deactivate this `if` statement to skip evaluation on musdb: `https://github.com/facebookresearch/demucs/blob/main/demucs/solver.py#L266`
> 
> Then finally, you can run an experiment with `dora run -d dset=my_dset`.

Commenting out line 80 led to variable errors. 

Here's what I did instead:

Change line 80 in https://github.com/facebookresearch/demucs/blob/main/demucs/train.py#L80 from

`    train_set, valid_set = get_musdb_wav_datasets(args.dset)`

To 

`    train_set, valid_set = get_wav_datasets(args.dset)`

This way is sees my referenced dataset as the main one.

**Comment by Anjok07** [comment]
> 

@K3nn3th2 [K3nn3th2](https://github.com/K3nn3th2) After much trial and error, I'm finally getting robust results using our big dataset! I'll post updates when training has been completed.

**Comment by jie-chen** [comment]
> So it is possible, but with a bit of hacking. Comment the following line so that the musdb dataset is not loaded: https://github.com/facebookresearch/demucs/blob/main/demucs/train.py#L80
> 
> Create a folder with `train` and `valid` subfolders and in each put one folder per track, with three files: `vocals.wav`, `non_vocals.wav`, `mixture.wav`.
> 
> Then create a file in `conf/dset/my_dset.yaml` and change the paths (like https://github.com/facebookresearch/demucs/blob/main/conf/dset/extra44.yaml), and add a line to have something like:
> 
> ```
> dset:
>   wav: ...
>   ...
>   sources: ['vocals', 'non_vocals']
> ```
> 
> You might want to deactivate this `if` statement to skip evaluation on musdb: `https://github.com/facebookresearch/demucs/blob/main/demucs/solver.py#L266`
> 
> Then finally, you can run an experiment with `dora run -d dset=my_dset`.

It seems the training wavset use sum of sources instead of mixture file as shown here https://github.com/facebookresearch/demucs/blob/main/demucs/solver.py#L308 . Does it make a difference if mixture file is used instead?

**Comment by person-29** [comment]
> So it is possible, but with a bit of hacking. Comment the following line so that the musdb dataset is not loaded: https://github.com/facebookresearch/demucs/blob/main/demucs/train.py#L80
> 
> Create a folder with `train` and `valid` subfolders and in each put one folder per track, with three files: `vocals.wav`, `non_vocals.wav`, `mixture.wav`.
> 
> Then create a file in `conf/dset/my_dset.yaml` and change the paths (like https://github.com/facebookresearch/demucs/blob/main/conf/dset/extra44.yaml), and add a line to have something like:
> 
> ```
> dset:
>   wav: ...
>   ...
>   sources: ['vocals', 'non_vocals']
> ```
> 
> You might want to deactivate this `if` statement to skip evaluation on musdb: `https://github.com/facebookresearch/demucs/blob/main/demucs/solver.py#L266`
> 
> Then finally, you can run an experiment with `dora run -d dset=my_dset`.

Is it necessary for the sources to be called 'vocals' and 'non_vocals' or would any other name work?

**Comment by CarlGao4** [comment]
You can use any name except "mixture"
