### ISSUE TITLE
No module named 'dora.explore'

### ISSUE THREAD

**Issue by OktoberfestThePlayer** [facebookresearch/demucs#232]
Hello! I recently installed the new Demucs V3 and for some reason after updating it, it gives me this traceback for some reason, do you know why it happens?

(demucs) C:\Users\Diego\Documents\demucs-main>python -m demucs.separate -n demucs -d cpu --shifts=10 heroinstrumental.wav
Traceback (most recent call last):
  File "C:\Users\Diego\anaconda3\envs\demucs\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Diego\anaconda3\envs\demucs\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Diego\Documents\demucs-main\demucs\separate.py", line 12, in <module>
    from dora.log import fatal
  File "C:\Users\Diego\anaconda3\envs\demucs\lib\site-packages\dora\__init__.py", line 66, in <module>
    from .explore import Explorer, Launcher
ModuleNotFoundError: No module named 'dora.explore'

**Comment by adefossez** [comment]
Do 'python -m pip install dora-search' 
I think I've updated the conda files but maybe I missed a place!

**Comment by OktoberfestThePlayer** [comment]
Now it works! Thank you!
