### ISSUE TITLE
cannot import name 'restore_quantized_state' from 'diffq'

### ISSUE THREAD

**Issue by MaxiReggi** [facebookresearch/demucs#238]
## ❓ Questions

Hi! I'm trying to test Demucs V3! But when I try to separate some track, It gives me the following error (with V2 it didn´t happen and worked perfectly):

Traceback (most recent call last):
  File "C:\Users\maxim\anaconda3\envs\demucs\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\maxim\anaconda3\envs\demucs\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Demucs_Source\V3\demucs\demucs\separate.py", line 16, in <module>
    from .apply import apply_model, BagOfModels
  File "C:\Demucs_Source\V3\demucs\demucs\apply.py", line 18, in <module>
    from .demucs import Demucs
  File "C:\Demucs_Source\V3\demucs\demucs\demucs.py", line 15, in <module>
    from .states import capture_init
  File "C:\Demucs_Source\V3\demucs\demucs\states.py", line 19, in <module>
    from diffq import DiffQuantizer, UniformQuantizer, restore_quantized_state
ImportError: cannot import name 'restore_quantized_state' from 'diffq' (C:\Users\maxim\anaconda3\envs\demucs\lib\site-packages\diffq\__init__.py)

The command I'm running is the following:

python -m demucs.separate -n mdx_extra --shifts=10 -o C:\Demucs_Output "C:\R.E.M. - Bad Day.wav"
(I have GPU)

Thank you very much!!! Thanks @adefossez for all the work and support!

**Comment by MaxiReggi** [comment]
Ok, I think that I've found the issue. Now I'm working but when I cant test it, I will post again.

Cheers!

**Comment by MaxiReggi** [comment]
Well I could resolve the issue!

I noticed that in environment-cuda.yml the version of diffq is different that the one in environment-cpu.yml, and openunmix is not included too, so adding the following to environemnt-cuda.yml solved the problem:

- diffq>=0.2 (remove diffq<0.2.0)
- openunmix

@adefossez when you can, you can change this in the file. Thank you for your effort and support!

Cheers

Maxi

**Comment by MaxiReggi** [comment]
I just listened to the separated tracks on my DAW, is AN INCREDIBLE DIFFERENCE with the V2 quality!! 

Thanks @adefossez for this job, is really amazing!!!!

And sorry for all the labels to you on this post.

Greetings,

Maxi

**Comment by adefossez** [comment]
I have changed the requirements ! thanks for finding the issue and the fix :)

Glad you enjoy the new version !!
