### ISSUE TITLE
Help importing the numpy C-extenstions failed.

### ISSUE THREAD

**Issue by lesaintdemon** [facebookresearch/demucs#245]
OS: Windows 10 (64 bit)

(demucs) PS C:\demucs> demucs -d cpu "C:\demucs\test.mp3"
C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py:143: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\demucs-script.py", line 33, in <module>
    sys.exit(load_entry_point('demucs', 'console_scripts', 'demucs')())
  File "C:\ProgramData\Anaconda3\Scripts\demucs-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\ProgramData\Anaconda3\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\demucs\demucs\separate.py", line 12, in <module>
    from dora.log import fatal
  File "C:\ProgramData\Anaconda3\lib\site-packages\dora\__init__.py", line 66, in <module>
    from .explore import Explorer, Launcher
  File "C:\ProgramData\Anaconda3\lib\site-packages\dora\explore.py", line 27, in <module>
    from .shep import Shepherd, Sheep
  File "C:\ProgramData\Anaconda3\lib\site-packages\dora\shep.py", line 25, in <module>
    from .distrib import get_distrib_spec
  File "C:\ProgramData\Anaconda3\lib\site-packages\dora\distrib.py", line 12, in <module>
    import torch
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\__init__.py", line 613, in <module>
    _C._initExtension(manager_path())
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 685, in <module>
    from . import amp
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\amp\__init__.py", line 1, in <module>
    from .autocast_mode import autocast, custom_fwd, custom_bwd  # noqa: F401
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\amp\autocast_mode.py", line 5, in <module>
    import numpy as np
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py", line 145, in <module>
    from . import core
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\ProgramData\Anaconda3\python.exe"
  * The NumPy version is: "1.20.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

Help me I'm not the best at coding and honestly don't know what to do

**Comment by adefossez** [comment]
Could you try running `conda env update -f environment-cpu.yml` and trying again ?
This is a weird error, normally anaconda should take care of all the dependencies...

**Comment by lesaintdemon** [comment]
thanks for the fast response, i uninstalled anaconda and pyhton and re-installed just anaconda and did everything again, and now it's working, thanks

**Comment by adefossez** [comment]
Nice to see the main fix for computer issues is still some variant of "turn it off and turn it on again" :D 
I will close the issue then.
