### ISSUE TITLE
Installation fails on MacOS (conflicting dependencies)

### ISSUE THREAD

**Issue by PierreMarieRiviere** [facebookresearch/demucs#246]
## 🐛 Bug Report

`python3 -m pip install --user -U demucs` command fails on MacOS. 

Running:
- BigSur v11.6 on M1 chip
- Python 3.10.1 with pip-21.3.1

## To Reproduce

1. Run `python3 -m pip install --user -U demucs`

## Expected behavior

Returns
```
Collecting demucs
  Using cached demucs-3.0.1.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
Collecting dora-search
  Using cached dora_search-0.1.7.tar.gz (68 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting demucs
  Using cached demucs-3.0.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_3d8567b52f024f7a8b8e2e3c8e5db5d6/setup.py'"'"'; __file__='"'"'/private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_3d8567b52f024f7a8b8e2e3c8e5db5d6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-pip-egg-info-92s0nt5s
       cwd: /private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_3d8567b52f024f7a8b8e2e3c8e5db5d6/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_3d8567b52f024f7a8b8e2e3c8e5db5d6/setup.py", line 39, in <module>
      REQUIRED = load_requirements('requirements_minimal.txt')
    File "/private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_3d8567b52f024f7a8b8e2e3c8e5db5d6/setup.py", line 34, in load_requirements
      required = [i.strip() for i in open(HERE / name)]
  FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_3d8567b52f024f7a8b8e2e3c8e5db5d6/requirements_minimal.txt'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/5b/a5/d29ca8f45f1d6dc814d595b9874cb209d45e97c1bbfb41c48968be2e1231/demucs-3.0.0.tar.gz#sha256=d91beb476dfec0362a531a935429f429f3f8dae0d0772da3efb4fad73e9116d2 (from https://pypi.org/simple/demucs/) (requires-python:>=3.7.0). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached demucs-2.0.3.tar.gz (51 kB)
  Preparing metadata (setup.py) ... done
Collecting diffq>=0.1
  Using cached diffq-0.2.0.tar.gz (39 kB)
  Preparing metadata (setup.py) ... done
Collecting demucs
  Using cached demucs-2.0.2.tar.gz (51 kB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-2.0.1.tar.gz (51 kB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-2.0.0.tar.gz (45 kB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-0.0.2.tar.gz (45 kB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-0.0.1.tar.gz (45 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_0a29a721dbf14a6384fcc442088ce467/setup.py'"'"'; __file__='"'"'/private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_0a29a721dbf14a6384fcc442088ce467/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-pip-egg-info-n7xrmiyp
       cwd: /private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_0a29a721dbf14a6384fcc442088ce467/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_0a29a721dbf14a6384fcc442088ce467/setup.py", line 25, in <module>
      REQUIRED = [i.strip() for i in open(HERE / "requirements.txt")]
  FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_0a29a721dbf14a6384fcc442088ce467/requirements.txt'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f0/0b/ebb129e8724e8822e8f94e231118109f73b4a77ff76d47142e0fced854d7/demucs-0.0.1.tar.gz#sha256=76841228f4befedd0e94387c0a0f03e0b3ab8aacf40001a8f4b062b28160535d (from https://pypi.org/simple/demucs/) (requires-python:>=3.7.0). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached demucs-0.0.0.tar.gz (1.5 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_2926f03aaabc4535a74e279043def8ca/setup.py'"'"'; __file__='"'"'/private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_2926f03aaabc4535a74e279043def8ca/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-pip-egg-info-tw41krwz
       cwd: /private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_2926f03aaabc4535a74e279043def8ca/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/s0/ks_8g5zn125076cpkskl_rvc0000gn/T/pip-install-e05p_m7_/demucs_2926f03aaabc4535a74e279043def8ca/setup.py", line 19, in <module>
      REQUIRED = [i.strip() for i in open("requirements.txt")]
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/80/04/5d0473a2e1261c3789ff6083febb5f797776a42dbbe069691b9cc73c9f10/demucs-0.0.0.tar.gz#sha256=8050de572ca5806244a28130b71b81d2542a02ebb91f37ff727becd7eb03debf (from https://pypi.org/simple/demucs/) (requires-python:>=3.7.0). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Cannot install demucs==0.0.2, demucs==2.0.0, demucs==2.0.1, demucs==2.0.2, demucs==2.0.3 and demucs==3.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    demucs 3.0.1 depends on diffq>=0.2.1
    demucs 2.0.3 depends on lameenc>=1.2
    demucs 2.0.2 depends on lameenc>=1.2
    demucs 2.0.1 depends on lameenc>=1.2
    demucs 2.0.0 depends on lameenc>=1.2
    demucs 0.0.2 depends on lameenc>=1.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

## Your Environment

- BigSur v11.6 on M1 chip, 16GB RAM
- Python 3.10.1 with pip-21.3.1

**Comment by adefossez** [comment]
What happens if you run `pip install --user -U diffq>=0.2.1` ? do you have `xcode` installed ? the issue is that `diffq` is not pre-compiled for M1, so you would have to install it with your own compiler, but I would expect this to happen automatically.

**Comment by PierreMarieRiviere** [comment]
I just have `xcode` `CommandLineTools` installed, do I need the full Xcode?

`pip install --user -U diffq>=0.2.1` returns `zsh: 0.2.1 not found`. Not too sure what to do from here.

**Comment by adefossez** [comment]
Sorry I forgot to add quotes, the command should be `pip install --user -U 'diffq>=0.2.1'`

I think CommandLineTools should be enough, not sure, one way to check is if the `clang` command works from the terminal.

**Comment by PierreMarieRiviere** [comment]
Thanks so much for getting back to this. The command 'pip install --user -U 'diffq>=0.2.1' does not work, I get
```
ERROR: Could not find a version that satisfies the requirement diffq>=0.2.1 (from versions: 0.0.1, 0.1.0, 0.1.1, 0.2.0)
ERROR: No matching distribution found for diffq>=0.2.1
```

`clang` not working either giving `error: no input files`

Any idea how to troubleshoot this?

**Comment by adefossez** [comment]
My bad, I had forgotten to include the source distribution for `diffq`, only the pre-compiled ones. I have uploaded the sources to PyPI now. Can you retry the command `pip install --user -U 'diffq>=0.2.1' `, it should work now :)

You do have clang installed, so no issues on that side !

**Comment by PierreMarieRiviere** [comment]
Damn, still getting an error after your update, see:

```
Collecting diffq>=0.2.1
  Downloading diffq-0.2.2.tar.gz (44 kB)
     |████████████████████████████████| 44 kB 3.3 MB/s
  Preparing metadata (setup.py) ... done
Collecting Cython
  Downloading Cython-0.29.25-py2.py3-none-any.whl (983 kB)
     |████████████████████████████████| 983 kB 5.2 MB/s
Collecting numpy
  Downloading numpy-1.21.4-cp310-cp310-macosx_11_0_arm64.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 4.5 MB/s
ERROR: Could not find a version that satisfies the requirement torch (from diffq) (from versions: none)
ERROR: No matching distribution found for torch
```

**Comment by adefossez** [comment]
Yes, that one is because PyTorch is not provided for M1 architectures. There seems to be ways to install it though (see https://betterprogramming.pub/how-to-install-pytorch-on-apple-m1-series-512b3ad9bc6) but you would have to figure that one out.

**Comment by PierreMarieRiviere** [comment]
I could successfully install Demucs. Downgraded Python to v3.7.9 as advised here https://stackoverflow.com/a/70215508/7237293

Then I could run `python3 -m pip install --user -U demucs` succesfully.

However, trying `python3 -m demucs -d cpu ./desktop/playa.mp3`, it is not working:

Should i open another issue and close this, or are the problems related?

```
Downloading: "https://dl.fbaipublicfiles.com/demucs/mdx_final/83fc094f-4a16d450.th" to /Users/pierremarieriviere/.cache/torch/hub/checkpoints/83fc094f-4a16d450.th
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1447, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/__main__.py", line 10, in <module>
    main()
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/separate.py", line 94, in main
    model = get_model_from_args(args)
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/pretrained.py", line 66, in get_model_from_args
    return get_model(name=args.name, repo=args.repo)
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/pretrained.py", line 59, in get_model
    return any_repo.get_model(name)
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/repo.py", line 153, in get_model
    return self.bag_repo.get_model(name_or_sig)
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/repo.py", line 135, in get_model
    models = [self.model_repo.get_model(sig) for sig in signatures]
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/repo.py", line 135, in <listcomp>
    models = [self.model_repo.get_model(sig) for sig in signatures]
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/repo.py", line 71, in get_model
    pkg = torch.hub.load_state_dict_from_url(url, map_location='cpu', check_hash=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/hub.py", line 586, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/hub.py", line 452, in download_url_to_file
    u = urlopen(req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
➜  music_tests python3 -m demucs -d cpu ./desktop/playa
Downloading: "https://dl.fbaipublicfiles.com/demucs/mdx_final/83fc094f-4a16d450.th" to /Users/pierremarieriviere/.cache/torch/hub/checkpoints/83fc094f-4a16d450.th
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1447, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/__main__.py", line 10, in <module>
    main()
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/separate.py", line 94, in main
    model = get_model_from_args(args)
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/pretrained.py", line 66, in get_model_from_args
    return get_model(name=args.name, repo=args.repo)
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/pretrained.py", line 59, in get_model
    return any_repo.get_model(name)
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/repo.py", line 153, in get_model
    return self.bag_repo.get_model(name_or_sig)
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/repo.py", line 135, in get_model
    models = [self.model_repo.get_model(sig) for sig in signatures]
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/repo.py", line 135, in <listcomp>
    models = [self.model_repo.get_model(sig) for sig in signatures]
  File "/Users/pierremarieriviere/Library/Python/3.7/lib/python/site-packages/demucs/repo.py", line 71, in get_model
    pkg = torch.hub.load_state_dict_from_url(url, map_location='cpu', check_hash=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/hub.py", line 586, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/hub.py", line 452, in download_url_to_file
    u = urlopen(req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
```

**Comment by adefossez** [comment]
how did you install python ?

**Comment by adefossez** [comment]
If you installed directly using the installer from python.org, then this might help you: https://stackoverflow.com/a/53310545/2936604

**Comment by PierreMarieRiviere** [comment]
Genius. Solved. Sorry shoulda found this by myself.

Thanks for the great work + support, really excited about this tool!
