### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'submit'

### ISSUE THREAD

**Issue by psshin** [facebookresearch/demucs#258]
## 🐛 Bug Report

Trying to separate vocals in .mp3 in Colab with no issues the other day but now running into this AttributeError.

I upload .mp3 and change demucs.separate path to .mp3 and then get this message:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/demucs/separate.py", line 142, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/demucs/separate.py", line 127, in main
    num_workers=args.jobs)[0]
  File "/usr/local/lib/python3.7/dist-packages/demucs/apply.py", line 167, in apply_model
    out = apply_model(sub_model, mix, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/demucs/apply.py", line 202, in apply_model
    future = pool.submit(apply_model, model, chunk, **kwargs)
AttributeError: 'NoneType' object has no attribute 'submit'

**Comment by adefossez** [comment]
sorry about that, should be fixed now if you run `python3 -m pip install -U demucs`.

**Comment by psshin** [comment]
Works great now, thanks!
