### ISSUE TITLE
RuntimeError: No audio I/O backend is available. &  doesn't export wav files

### ISSUE THREAD

**Issue by maaagdonals** [facebookresearch/demucs#260]
(Using Anaconda prompt with Win10)
Everytime after I execute the commands with demucs I get this:
C:\Users\Mag\anaconda3\lib\site-packages\torchaudio\backend\utils.py:67: UserWarning: No audio backend is available.
  warnings.warn('No audio backend is available.')
(Separates tracks)
Traceback (most recent call last):
  File "C:\Users\Mag\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Mag\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mag\anaconda3\Scripts\demucs.exe\__main__.py", line 7, in <module>
  File "C:\Users\Mag\anaconda3\lib\site-packages\demucs\separate.py", line 136, in main
    save_audio(source, stem, model.samplerate)
  File "C:\Users\Mag\anaconda3\lib\site-packages\demucs\audio.py", line 247, in save_audio
    ta.save(str(path), wav, sample_rate=samplerate)
  File "C:\Users\Mag\anaconda3\lib\site-packages\torchaudio\backend\no_backend.py", line 18, in save
    raise RuntimeError('No audio I/O backend is available.')
RuntimeError: No audio I/O backend is available.

Now, if I specified to export the tracks as mp3 files, demucs creates a directory with the original file's name and leaves the 4 tracks as expected. However, if I want the tracks as .wav files, demucs only creates the directory with no files inside.
What do I have to do in order to solve this problem?

**Comment by adefossez** [comment]
This is because you do not have ffmpeg installed. `conda install -f conda-forge ffmpeg` should solve the issue (you need to do so from the conda env defined for demucs, so after `conda activate demucs` if you followed the installation instructions for windows).

**Comment by maaagdonals** [comment]
Thanks, after uninstalling and installing it again (and realizing it's `conda install -c conda-forge ffmpeg` instead of `conda install -f conda-forge ffmpeg`) it finally worked. Again, I'm deeply thankful for the help!
