### ISSUE TITLE
RuntimeError: Nothing to restore. This shouldn't happen. add --diffq

### ISSUE THREAD

**Issue by Beninmiao** [facebookresearch/demucs#265]
## ❓ Questions
Hi! I'm trying to train convtasnet V2. But I have some problem when I use --diffq. When I add this command, it will broken in valid.

[000] valid:   0%|                                                                            | 0/2 [00:00<?, ? track/s]Traceback (most recent call last):
  File "/mnt/disk/Users/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/disk/Users/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/disk/Users/musdb/demucs/demucs/__main__.py", line 343, in <module>
    main()
  File "/mnt/disk/Users/musdb/demucs/demucs/__main__.py", line 260, in main
    valid_loss = validate_model(epoch,
  File "/mnt/disk/Users/musdb/demucs/demucs/train.py", line 121, in validate_model
    estimates = apply_model(model, mix, shifts=shifts, split=split, overlap=overlap)
  File "/mnt/disk/Users/musdb/demucs/demucs/utils.py", line 197, in apply_model
    chunk_out = apply_model(model, chunk, shifts=shifts)
  File "/mnt/disk/Users/musdb/demucs/demucs/utils.py", line 225, in apply_model
    out = model(padded_mix.unsqueeze(0))[0]
  File "/mnt/disk/Users/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1123, in _call_impl
    hook_result = hook(self, input, result)
  File "/mnt/disk/Users/anaconda3/envs/pytorch/lib/python3.8/site-packages/diffq/base.py", line 105, in _forward_hook
    self.unquantize()
  File "/mnt/disk/Users/anaconda3/envs/pytorch/lib/python3.8/site-packages/diffq/base.py", line 141, in unquantize
    raise RuntimeError("Nothing to restore. This shouldn't happen")
RuntimeError: Nothing to restore. This shouldn't happen

The command I'm running is the following:
python3 run.py --musdb /mnt/disk/musdb18/ --tasnet --samples=80000  --is_wav -b 32 --X=10  --diffq 1 

If there is no --diffq, it will be ok!

**Comment by adefossez** [comment]
Do you need the `diffq` on that one ? convtasnet is already quite small so there is not much gain quantizing it !

**Comment by cst781** [comment]
but the computation cost  of convtasnet is too high， how could we reduce the computation cost？

**Comment by adefossez** [comment]
`diffq` wont reduce the  computation of convtasnet, only the model size, which is already quite small. There is no real way to reduce the computation cost of convtasnet (except reducing number of channels or depth but that will reduce the efficiency).
