### ISSUE TITLE
Couldn't use cuda for splitting mp3, pls help me

### ISSUE THREAD

**Issue by Zakirzhan** [facebookresearch/demucs#270]
```
(demucs) root@C.2162913:~/demucs$ **### python3 -m demucs --mp3 --mp3-bitrate 128 123.mp3 -d cuda**
/root/anaconda3/envs/demucs/lib/python3.8/site-packages/torchaudio/_internal/module_utils.py:87: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
  warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")
Selected model is a bag of 4 models. You will see that many progress bars per track.
Separated tracks will be stored in /root/demucs/separated/mdx_extra_q
Separating track 123.mp3
ffprobe: error while loading shared libraries: libopenh264.so.5: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/root/anaconda3/envs/demucs/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/demucs/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/demucs/demucs/__main__.py", line 10, in <module>
    main()
  File "/root/demucs/demucs/separate.py", line 123, in main
    sources = apply_model(model, wav[None], device=args.device, shifts=args.shifts,
  File "/root/demucs/demucs/apply.py", line 165, in apply_model
    sub_model.to(device)
  File "/root/anaconda3/envs/demucs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 899, in to
    return self._apply(convert)
  File "/root/anaconda3/envs/demucs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/root/anaconda3/envs/demucs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/root/anaconda3/envs/demucs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/root/anaconda3/envs/demucs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 593, in _apply
    param_applied = fn(param)
  File "/root/anaconda3/envs/demucs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/root/anaconda3/envs/demucs/lib/python3.8/site-packages/torch/cuda/__init__.py", line 208, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
**AssertionError: Torch not compiled with CUDA enabled**
```

I rent a server in [vast.ai](https://vast.ai/)
but after installing demucs, only via cpu it works, but doesn't work via cuda

**Comment by CarlGao4** [comment]
Maybe you didn't install coda version for Torch, which is default. Please run `pip uninstall torch torchaudio` and visit [https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/). Choose your CUDA version and follow the instructions on it.

**Comment by CarlGao4** [comment]
I also noticed that you didn't install pySoundFile, which may lead to failure of reading audio files. If this happens, please try running `pip install pySoundFile`.
