### ISSUE TITLE
ModuleNotFoundError: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by SZ87** [facebookresearch/demucs#275]
I initially began using demucs in cpu mode, but figured I'd try with cuda. Following [these steps](https://github.com/facebookresearch/demucs/blob/main/docs/windows.md#windows-support-for-demucs) again, but changing `conda env update -f environment-cpu.yml` to `conda env update -f environment-cuda.yml` instead, I get the following output after trying to run it:

```
Traceback (most recent call last):
  File "C:\anaconda3\envs\demucs\Scripts\demucs-script.py", line 11, in <module>
    load_entry_point('demucs', 'console_scripts', 'demucs')()
  File "C:\anaconda3\envs\demucs\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\anaconda3\envs\demucs\lib\site-packages\pkg_resources\__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "C:\anaconda3\envs\demucs\lib\site-packages\pkg_resources\__init__.py", line 2445, in load
    return self.resolve()
  File "C:\anaconda3\envs\demucs\lib\site-packages\pkg_resources\__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\steven zambelle\demucs\demucs\separate.py", line 14, in <module>
    import torchaudio as ta
  File "C:\anaconda3\envs\demucs\lib\site-packages\torchaudio\__init__.py", line 13, in <module>
    from torchaudio.backend import (
  File "C:\anaconda3\envs\demucs\lib\site-packages\torchaudio\backend\__init__.py", line 2, in <module>
    from . import utils
  File "C:\anaconda3\envs\demucs\lib\site-packages\torchaudio\backend\utils.py", line 7, in <module>
    from . import (
  File "C:\anaconda3\envs\demucs\lib\site-packages\torchaudio\backend\soundfile_backend.py", line 11, in <module>
    import soundfile
  File "C:\anaconda3\envs\demucs\lib\site-packages\soundfile.py", line 17, in <module>
    from _soundfile import ffi as _ffi
  File "C:\anaconda3\envs\demucs\lib\site-packages\_soundfile.py", line 2, in <module>
    import _cffi_backend
ModuleNotFoundError: No module named '_cffi_backend'
```
The above error is also now received when specifying `cpu`.

Here is the output from running `conda list`:

```
# packages in environment at C:\anaconda3\envs\demucs:
#
# Name                    Version                   Build  Channel
antlr4-python3-runtime    4.8                      pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
blas                      2.113                       mkl    conda-forge
blas-devel                3.9.0              13_win64_mkl    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
certifi                   2021.10.8        py38haa244fe_1    conda-forge
cffi                      1.15.0                   pypi_0    pypi
cloudpickle               2.0.0                    pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colorlog                  6.6.0                    pypi_0    pypi
cpuonly                   1.0                           0    pytorch
cudatoolkit               11.6.0               hc0ea762_9    conda-forge
cython                    0.29.26                  pypi_0    pypi
demucs                    3.0.4a0                   dev_0    <develop>
diffq                     0.2.2                    pypi_0    pypi
dora-search               0.1.8                    pypi_0    pypi
ffmpeg                    4.3                  ha925a31_0    pytorch
ffmpeg-python             0.2.0                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
hydra-colorlog            1.1.0                    pypi_0    pypi
hydra-core                1.1.1                    pypi_0    pypi
importlib-resources       5.4.0                    pypi_0    pypi
intel-openmp              2022.0.0          h57928b3_3663    conda-forge
jsonschema                4.4.0                    pypi_0    pypi
julius                    0.2.6                    pypi_0    pypi
lameenc                   1.3.1                    pypi_0    pypi
libblas                   3.9.0              13_win64_mkl    conda-forge
libcblas                  3.9.0              13_win64_mkl    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
liblapack                 3.9.0              13_win64_mkl    conda-forge
liblapacke                3.9.0              13_win64_mkl    conda-forge
libuv                     1.43.0               h8ffe710_0    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mkl                       2022.0.0           h0e2418a_796    conda-forge
mkl-devel                 2022.0.0           h57928b3_797    conda-forge
mkl-include               2022.0.0           h0e2418a_796    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
musdb                     0.4.0                    pypi_0    pypi
museval                   0.4.0                    pypi_0    pypi
ninja                     1.10.2               h2d74725_1    conda-forge
numpy                     1.18.1           py38hc71023c_0    conda-forge
omegaconf                 2.1.1                    pypi_0    pypi
openssl                   3.0.0                h8ffe710_2    conda-forge
openunmix                 1.2.1                    pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pyaml                     21.10.1                  pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
python                    3.8.12          h900ac77_2_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.9.1               py3.8_cpu_0  [cpuonly]  pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2021.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                45.2.0                   py38_0    conda-forge
simplejson                3.17.6                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
soundfile                 0.10.3.post1             pypi_0    pypi
sqlite                    3.37.0               h8ffe710_0    conda-forge
stempeg                   0.2.3                    pypi_0    pypi
submitit                  1.4.1                    pypi_0    pypi
tbb                       2021.5.0             h2d74725_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
torchaudio                0.9.1                      py38    pytorch
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
treetable                 0.2.5                    pypi_0    pypi
typing_extensions         4.0.1              pyha770c72_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zipp                      3.7.0                    pypi_0    pypi
```
Do I simply delete demucs and re-clone?

ETA: The answer to the above question is "No".

**Comment by SZ87** [comment]
This issue is resolved after uninstalling then reinstalling Anaconda.
