### ISSUE TITLE
Failed to import module demucs.train

### ISSUE THREAD

**Issue by lyndonlauder** [facebookresearch/demucs#310]
Hi, I get this error when I try to run !dora run -d -f 81de367c . Thank you for any help please

INFO:dora.utils:Could not import module demucs.train
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dora/utils.py", line 77, in import_or_fatal
    return importlib.import_module(module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/demucs/demucs/train.py", line 14, in <module>
    from dora import hydra_main
ImportError: cannot import name 'hydra_main' from 'dora' (/usr/local/lib/python3.7/site-packages/dora/__init__.py)
FATAL: Failed to import module demucs.train.

**Comment by lyndonlauder** [comment]
Fixed by installing requirements.txt
