### ISSUE TITLE
I can't separate songs in Ubuntu 20.04. [SSL:WRONG_VERSION_NUMBER]

### ISSUE THREAD

**Issue by gbrea** [facebookresearch/demucs#321]
## 🐛 Bug Report

Hello. I'm trying to use the software following the instructions in the repository, but I can't get there.
I attach the error output below.

## To Reproduce

1. Install `pip3` with `sudo apt install python3-pip`
2. Install `demucs` with `python3 -m pip install -U demucs` or with `pip3 install --user -U demucs`, I have tried both ways
3. Try to detach a song with python3 -m demucs -d cpu PATH_TO_AUDIO_FILE_1
4. Returns the following error lines
```
guilherme@PC:~$ python3 -m demucs -d cpu Música/Ses\ -\ Liberar\ as\ arterias/02\ -\ Quen\ son\ os\ meus.mp3 
Downloading: "https://dl.fbaipublicfiles.com/demucs/mdx_final/464b36d7-e5a9386e.th" to /home/guilherme/.cache/torch/hub/checkpoints/464b36d7-e5a9386e.th
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1425, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/guilherme/.local/lib/python3.8/site-packages/demucs/__main__.py", line 10, in <module>
    main()
  File "/home/guilherme/.local/lib/python3.8/site-packages/demucs/separate.py", line 109, in main
    model = get_model_from_args(args)
  File "/home/guilherme/.local/lib/python3.8/site-packages/demucs/pretrained.py", line 66, in get_model_from_args
    return get_model(name=args.name, repo=args.repo)
  File "/home/guilherme/.local/lib/python3.8/site-packages/demucs/pretrained.py", line 59, in get_model
    return any_repo.get_model(name)
  File "/home/guilherme/.local/lib/python3.8/site-packages/demucs/repo.py", line 153, in get_model
    return self.bag_repo.get_model(name_or_sig)
  File "/home/guilherme/.local/lib/python3.8/site-packages/demucs/repo.py", line 135, in get_model
    models = [self.model_repo.get_model(sig) for sig in signatures]
  File "/home/guilherme/.local/lib/python3.8/site-packages/demucs/repo.py", line 135, in <listcomp>
    models = [self.model_repo.get_model(sig) for sig in signatures]
  File "/home/guilherme/.local/lib/python3.8/site-packages/demucs/repo.py", line 71, in get_model
    pkg = torch.hub.load_state_dict_from_url(url, map_location='cpu', check_hash=True)
  File "/home/guilherme/.local/lib/python3.8/site-packages/torch/hub.py", line 591, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/guilherme/.local/lib/python3.8/site-packages/torch/hub.py", line 457, in download_url_to_file
    u = urlopen(req)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)>
```

## Your Environment

- Python and PyTorch version: `Python 3.8` , `PyTorch 1.11.0+cu102`
- Operating system and version (desktop or mobile): `Ubuntu 20.04.1`
- Hardware (gpu or cpu, amount of RAM etc.): CPU `AMD Ryzen 5 1600 Six-Core Processor`, GPU `NVIDIA GeForce GT 710`, `16GB DDR4` RAM

**Comment by gbrea** [comment]
I have tried again and now it completes the task successfully.
Could it be a temporary network problem?

**Comment by calebho** [comment]
I'm in the midst of migrating some stuff on the backend and it seems I misconfigured something. This misconfiguration should be fixed since yesterday. Apologies for the inconvenience
