### ISSUE TITLE
i have this problem - tengo este problema 

### ISSUE THREAD

**Issue by klauz996** [facebookresearch/demucs#34]
(demucs) C:\Users\Chrisitan\Desktop\demucs-master>python.exe -m demucs.separate --dl -n demucs "C:\Users\Chrisitan\Desktop\demucs-master\alex estella   dime.mp3"
Traceback (most recent call last):
  File "C:\Users\Chrisitan\Anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Chrisitan\Anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Chrisitan\Desktop\demucs-master\demucs\separate.py", line 143, in <module>
    main()
  File "C:\Users\Chrisitan\Desktop\demucs-master\demucs\separate.py", line 122, in main
    model = th.load(model_path).to(args.device)
  File "C:\Users\Chrisitan\Anaconda3\envs\demucs\lib\site-packages\torch\serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Chrisitan\Anaconda3\envs\demucs\lib\site-packages\torch\serialization.py", line 620, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 123420503 more bytes. The file might be corrupted.

**Comment by PabloVargas19** [comment]
tienes que hacer lo mismo de poner python.exe -m demucs.separate --dl -n demucs "C:\Users\Chrisitan\Desktop\demucs-master\alex estella dime.mp3" pero antes de poner enter tienes que borrar el archivo demucs.th que esta en la dirección \demucs-master\models

**Comment by klauz996** [comment]
> tienes que hacer lo mismo de poner python.exe -m demucs.separate --dl -n demucs "C:\Users\Chrisitan\Desktop\demucs-master\alex estella dime.mp3" pero antes de poner enter tienes que borrar el archivo demucs.th que esta en la dirección \demucs-master\models

muchas gracias era eso mismo!!!

**Comment by adefossez** [comment]
Gracias @PabloVargas19  para ayudar !

**Comment by Richa312rds** [comment]
Pablo Vargas 19 donde esta la direccino \demucs-master\models no la encuentro, esta en la carpeta demuc master o en el terminal de anaconda..

**Comment by PabloVargas19** [comment]
> Pablo Vargas 19 donde esta la direccino \demucs-master\models no la encuentro, esta en la carpeta demuc master o en el terminal de anaconda..

esta en la carpeta de demucs master
