### ISSUE TITLE
automix.py doesn't work

### ISSUE THREAD

**Issue by Ryuklear** [facebookresearch/demucs#343]
## ❓ Questions
I'm using demucs v3 with anaconda with Windows10. I tried to run automix.py but it doesn't work, so what should I do to solve this problem?
Enviroment

PS C:\Users\whois\Desktop\python_work_0114-\demucs_v3_0413\demucs> python.exe -m tools.automix
100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 386.99it/s]
100%|███████████████████████████████████████████████████████████████████████████████████| 86/86 [00:16<00:00,  5.20it/s]
-0.6515151515151516 156.60511363636363 112.34714673913044 FAILED TEMPO
-0.6893939393939394 156.60511363636363 126.04801829268293 FAILED TEMPO
-0.7045454545454546 156.60511363636363 132.51201923076923 FAILED TEMPO
Traceback (most recent call last):
  File "C:\Users\whois\anaconda3\envs\demucs_0413-\lib\runpy.py", line 194, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\whois\anaconda3\envs\demucs_0413-\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\whois\Desktop\python_work_0114-\demucs_v3_0413\demucs\tools\automix.py", line 354, in <module>
    main()
  File "C:\Users\whois\Desktop\python_work_0114-\demucs_v3_0413\demucs\tools\automix.py", line 338, in main
    track, origs = build_track(index, catalog)
  File "C:\Users\whois\Desktop\python_work_0114-\demucs_v3_0413\demucs\tools\automix.py", line 256, in build_track
    wav, spec = get_part(spec, src, dt, dp)
  File "C:\Users\whois\Desktop\python_work_0114-\demucs_v3_0413\demucs\tools\automix.py", line 220, in get_part
    wav = repitch(wav, dp, dt * 100, samplerate=SR, voice=source == 3)
  File "C:\Users\whois\Desktop\python_work_0114-\demucs_v3_0413\demucs\demucs\repitch.py", line 68, in repitch
    save_audio(wav, infile.name, samplerate, clip='clamp')
  File "C:\Users\whois\Desktop\python_work_0114-\demucs_v3_0413\demucs\demucs\audio.py", line 254, in save_audio
    encoding=encoding, bits_per_sample=bits_per_sample)
  File "C:\Users\whois\anaconda3\envs\demucs_0413-\lib\site-packages\torchaudio\backend\soundfile_backend.py", line 427, in save
    soundfile.write(file=filepath, data=src, samplerate=sample_rate, subtype=subtype, format=format)
  File "C:\Users\whois\anaconda3\envs\demucs_0413-\lib\site-packages\soundfile.py", line 431, in write
    subtype, endian, format, closefd) as f:
  File "C:\Users\whois\anaconda3\envs\demucs_0413-\lib\site-packages\soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\whois\anaconda3\envs\demucs_0413-\lib\site-packages\soundfile.py", line 1265, in _open
    "Error opening {0!r}: ".format(self.name))
  File "C:\Users\whois\anaconda3\envs\demucs_0413-\lib\site-packages\soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'C:\\Users\\whois\\AppData\\Local\\Temp\\tmpvqv1b4_5.wav': System error.

**Comment by CarlGao4** [comment]
This is a problem caused by libsndfile. I don't know how it happened, but it haven't saved a file on my computer (Windows 11) since this March. It also failed on macOS 10.15.

**Comment by Ryuklear** [comment]
Thank you for your information. libsndfile is not included in requirements.txt, so how do I fix it?
@adefossez

**Comment by adefossez** [comment]
automix is used only for training. For training you should follow the instructions: https://github.com/facebookresearch/demucs#for-machine-learning-scientists

Those mention that you must create an anaconda env using the anaconda files provided, not the requirements.txt file which is only for evaluation.

**Comment by Ryuklear** [comment]
I tried to run with environment-cuda.yml for training, but i got a same error.

**Comment by adefossez** [comment]
Can you try running `conda install -c conda-forge libsndfile` ? I will add it the the environment-cuda.yml  file if that works.

**Comment by CarlGao4** [comment]
It won't help because libsndfile isn't a module in conda or pypi. What should we do is just waiting the developer of soundfile to fix this bug.

**Comment by adefossez** [comment]
There is a libsndfile in conda forge. Also have you run `python.exe -m pip install -U demucs PySoundFile` as provided in the Windows instructions ?
