### ISSUE TITLE
i have other problem - otro problema

### ISSUE THREAD

**Issue by klauz996** [facebookresearch/demucs#35]
Traceback (most recent call last):
  File "C:\Users\Chrisitan\Anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Chrisitan\Anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Chrisitan\Desktop\demucs-master\demucs\separate.py", line 143, in <module>
    main()
  File "C:\Users\Chrisitan\Desktop\demucs-master\demucs\separate.py", line 122, in main
    model = th.load(model_path).to(args.device)
  File "C:\Users\Chrisitan\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 426, in to
    return self._apply(convert)
  File "C:\Users\Chrisitan\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 202, in _apply
    module._apply(fn)
  File "C:\Users\Chrisitan\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 202, in _apply
    module._apply(fn)
  File "C:\Users\Chrisitan\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\rnn.py", line 124, in _apply
    self.flatten_parameters()
  File "C:\Users\Chrisitan\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\rnn.py", line 120, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: CUDA out of memory. Tried to allocate 1.53 GiB (GPU 0; 4.00 GiB total capacity; 2.34 GiB already allocated; 598.80 MiB free; 29.77 MiB cached)

 No me deja hacer mas nada

**Comment by rokimoki** [comment]
Ejecuta el comando tal cual como lo haces, poniendo `-d cpu` al final.
