### ISSUE TITLE
concurrent.futures.process.BrokenProcessPool

### ISSUE THREAD

**Issue by jim79** [facebookresearch/demucs#350]
## ❓ Questions
Hi,
I get the following error when executing tools.automix

`!python3 -m tools.automix`

`/usr/local/lib/python3.7/dist-packages/resampy/interpn.py:114: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 9107. The TBB threading layer is disabled.
  _resample_loop_p(x, t_out, interp_win, interp_delta, num_table, scale, y)
100%|█████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 85.84it/s]
  0%|                                                                                            | 0/86 [00:00<?, ?it/s]Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.
  0%|                                                                                            | 0/86 [00:11<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/demucsv3_jim/tools/automix.py", line 349, in <module>
    main()
  File "/content/demucsv3_jim/tools/automix.py", line 318, in main
    spec, track = pending.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.`

**Comment by adefossez** [comment]
See https://github.com/facebookresearch/demucs/issues/344

**Comment by adefossez** [comment]
can you try exporting the env variable `export NUMBA_NUM_THREADS=1` before running?

**Comment by SEMLLYCAT** [comment]
> 

Hello, I followed what you described, but it still didn't work

**Comment by SEMLLYCAT** [comment]
> `export NUMBA_NUM_THREADS=1`您可以尝试在运行前导出 env 变量吗？
Hello, I followed what you described, but it still didn't work
