### ISSUE TITLE
Errors when using --segment

### ISSUE THREAD

**Issue by BitBlueDevStudio** [facebookresearch/demucs#374]
## 🐛 Bug Report

If you use new --segment argument to decrease GPU memory usage, with some files you get AssertionError in hdemucs.py
For example, I used --segment=45 with RTX 3060 Nvidia GPU.

## To Reproduce

1. Set --segment to 45
1. Separate different audios
1. Get error

## Expected behavior

No errors. If you don't set --segment, you will never get errors like this.

## Actual Behavior

You get error:
```
0%|                                                                                   | 0.0/56.0 [00:00<?, ?seconds/s]
 50%|█████████████████████████████████████                                     | 28.0/56.0 [00:01<00:01, 20.87seconds/s]
 50%|█████████████████████████████████████                                     | 28.0/56.0 [00:01<00:01, 20.80seconds/s]
Traceback (most recent call last):
  File "/media/wa/ub-temp/anaconda3/envs/demucs/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/media/wa/ub-temp/anaconda3/envs/demucs/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/wa/ub-temp/demucs-main/demucs/separate.py", line 188, in <module>
    main()
  File "/media/wa/ub-temp/demucs-main/demucs/separate.py", line 153, in main
    sources = apply_model(model, wav[None], device=args.device, shifts=args.shifts,
  File "/media/wa/ub-temp/demucs-main/demucs/apply.py", line 208, in apply_model
    chunk_out = future.result()
  File "/media/wa/ub-temp/demucs-main/demucs/utils.py", line 119, in result
    return self.func(*self.args, **self.kwargs)
  File "/media/wa/ub-temp/demucs-main/demucs/apply.py", line 236, in apply_model
    out = model(padded_mix)
  File "/media/wa/ub-temp/anaconda3/envs/demucs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/wa/ub-temp/demucs-main/demucs/hdemucs.py", line 685, in forward
    z = self._spec(mix)
  File "/media/wa/ub-temp/demucs-main/demucs/hdemucs.py", line 602, in _spec
    assert z.shape[-1] == le   4, (z.shape, x.shape, le)
AssertionError: (torch.Size([1, 2, 2048, 7]), torch.Size([1, 2, 6369]), 1)
```

## Your Environment

- Python 3.8.13 and PyTorch 1.12
- Ubuntu 20.04
- RTX 3060 Nvidia GPU with 12GB memory

**Comment by CarlGao4** [comment]
I can't debug what happened on your computer. Can you upload your model and file.mp3?

**Comment by BitBlueDevStudio** [comment]
This bug reproducible with default models (mdx_extra, etc). What about audiofile, unfortunately, I can't share it

**Comment by CarlGao4** [comment]
I can't get this error. Can you reproduce this error on CPU using mdx_extra_q with an audio that you can share? I need to get this error myself to investigate.

**Comment by BitBlueDevStudio** [comment]
I thought --segment flag make sense only using GPU, so I'm not sure if you can reproduce this on CPU. I'll try to find some audio example which I can share

**Comment by CarlGao4** [comment]
Maybe it's true. Can you tell me what is the default segment of your model? I'm thinking that this may only occur when you set a `segment` bigger than default with GPU.

**Comment by BitBlueDevStudio** [comment]
I was able to reproduce it using mdx_exrta (not mdx_extra_q), which segment size is 44. I set segment to 40, also tried 15 and 10. As lower segment I set, so more often errors I get. With segment = 40 it's going on sometimes, but with 10 or 15 it's getting errors more often

**Comment by CarlGao4** [comment]
So... This becomes interesting.

**Comment by CarlGao4** [comment]
Does mdx_extra_q has the same result?

**Comment by adefossez** [comment]
Can you try again @BitBlueDevStudio  (installing from the repo, not from Pypi repo), there was a bug in pad1d and hopefully it should be fixed now.

**Comment by adefossez** [comment]
Sorry for the late reply, I would recommend `python3 -m pip install -U git+https://github.com/facebookresearch/demucs#egg=demucs` for the installation.

**Comment by arnavmehta7** [comment]
Is this still a bug? What's the normal segment value?

**Comment by CarlGao4** [comment]
The default segment depends on model. 
You can see that [the segment of `mdx_extra` is defined in yaml file. ](https://github.com/facebookresearch/demucs/blob/main/demucs/remote/mdx_extra.yaml#L2)
