### ISSUE TITLE
Installation failed on Red Hat

### ISSUE THREAD

**Issue by ljfreelancer88** [facebookresearch/demucs#377]
I'm trying to install Demucs on Red Hat shared hosting server :D but I got the error below. Is it possible to limit the memory or CPU usage during installation?

## 🐛 Bug Report

```bash
Downloading https://files.pythonhosted.org/packages/b9/af/23c13cd340cd333f42de225ba3da3b64e1a70425546d1a59bfa42d465a5d/torch-1.12.1-cp37-cp37m-manylinux1_x86_64.whl (776.3MB)
     |████████████████████████████████| 776.3MB 65.1MB/s eta 0:00:01ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/usr/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 379, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 296, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 244, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 347, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/usr/lib/python3.7/site-packages/pip/_internal/download.py", line 910, in unpack_url
    progress_bar=progress_bar
  File "/usr/lib/python3.7/site-packages/pip/_internal/download.py", line 746, in unpack_http_url
    progress_bar)
  File "/usr/lib/python3.7/site-packages/pip/_internal/download.py", line 978, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/usr/lib/python3.7/site-packages/pip/_internal/download.py", line 683, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python3.7/site-packages/pip/_internal/utils/hashes.py", line 62, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python3.7/site-packages/pip/_internal/download.py", line 651, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python3.7/site-packages/pip/_internal/utils/ui.py", line 156, in iter
    for x in it:
  File "/usr/lib/python3.7/site-packages/pip/_internal/download.py", line 640, in resp_read
    decode_content=False):
  File "/usr/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 531, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 479, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 65, in read
    self._close()
  File "/usr/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 52, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/lib/python3.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 300, in cache_response
    cache_url, self.serializer.dumps(request, response, body=body)
  File "/usr/lib/python3.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 72, in dumps
    return b",".join([b"cc=4", msgpack.dumps(data, use_bin_type=True)])
MemoryError
```

## Your Environment

Python 3.7.9
Red Hat 9.3.1-2 64-bit

**Comment by CarlGao4** [comment]
This is an issue due to pip. pip downloads the whole file into memory and checksum, which require large amount memory. Please download the file (https://files.pythonhosted.org/packages/b9/af/23c13cd340cd333f42de225ba3da3b64e1a70425546d1a59bfa42d465a5d/torch-1.12.1-cp37-cp37m-manylinux1_x86_64.whl) using other tools (aria2c, curl, wget, lynx, ...) and use `pip install local_file_path` instead. After that, run `pip install demucs` (or your original command) again.
