### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by OktoberfestThePlayer** [facebookresearch/demucs#406]
Hello!

I'm currently trying to test out the new Demucs4 with CUDA enable but I get this traceback saying that cuda is not enable/not working even though I just installed its toolkit, thank you!

(demucs) C:\Users\Diego\Documents\demucs>demucs -n htdemucs_ft -d cuda -o D:\Documents\Stems "F:\CD Rips\Ben Folds - Over The Hedge (Music from the Motion Picture)\1. Family of Me.flac"
Selected model is a bag of 4 models. You will see that many progress bars per track.
Separated tracks will be stored in D:\Documents\Stems\htdemucs_ft
Separating track F:\CD Rips\Ben Folds - Over The Hedge (Music from the Motion Picture)\1. Family of Me.flac
Traceback (most recent call last):
  File "C:\Users\Diego\anaconda3\envs\demucs\Scripts\demucs-script.py", line 33, in <module>
    sys.exit(load_entry_point('demucs', 'console_scripts', 'demucs')())
  File "c:\users\diego\documents\demucs\demucs\separate.py", line 163, in main
    sources = apply_model(model, wav[None], device=args.device, shifts=args.shifts,
  File "c:\users\diego\documents\demucs\demucs\apply.py", line 169, in apply_model
    sub_model.to(device)
  File "C:\Users\Diego\anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 987, in to
    return self._apply(convert)
  File "C:\Users\Diego\anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 639, in _apply
    module._apply(fn)
  File "C:\Users\Diego\anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 639, in _apply
    module._apply(fn)
  File "C:\Users\Diego\anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 639, in _apply
    module._apply(fn)
  File "C:\Users\Diego\anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 662, in _apply
    param_applied = fn(param)
  File "C:\Users\Diego\anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 985, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\Diego\anaconda3\envs\demucs\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by adefossez** [comment]
you didn't install Pytorch with cuda. 
please follow carefully the instructions there: https://github.com/facebookresearch/demucs/blob/main/docs/windows.md#if-you-want-to-use-your-gpu

You might need to upgrade your GPU drivers for compatibility with the latest versions of PyTorch. Only Nvidia gpus are supported. I'll close the issue, reopen after having followed the above instructions in case the issue persits.
