### ISSUE TITLE
RuntimeError: AYUDAAA

### ISSUE THREAD

**Issue by Gringo541** [facebookresearch/demucs#41]
cada vez que pongo un tema a separar me sale este problema ( lo resalto en negrita ) : 
(demucs) PS C:\Users\Usuario\demucs-master> python.exe -m demucs.separate --dl -n demucs C:\Users\Usuario\Desktop\IA\Tones
100%|█████████████████████████████████████████████████████████████████████████████| 2.59G/2.59G [32:14<00:00, 1.34MB/s]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Usuario\demucs-master\demucs\separate.py", line 143, in <module>
    main()
  File "C:\Users\Usuario\demucs-master\demucs\separate.py", line 122, in main
    model = th.load(model_path).to(args.device)
  File "C:\ProgramData\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 426, in to
    return self._apply(convert)
  File "C:\ProgramData\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 202, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 202, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\rnn.py", line 124, in _apply
    self.flatten_parameters()
  File "C:\ProgramData\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\rnn.py", line 120, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
**RuntimeError: CUDA out of memory. Tried to allocate 1.53 GiB (GPU 0; 4.00 GiB total capacity; 2.34 GiB already allocated; 467.68 MiB free; 29.77 MiB cached)**

**Comment by klauz996** [comment]
Ejecuta el comando tal cual como lo haces, poniendo -d cpu al final.

**Comment by Gringo541** [comment]
puse asi
python.exe -m demucs.separate --dl -n demucs -d cpu ( y la direccion del archivo )
 y me tira este error:

output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ffprobe', 'C:\Users\Usuario\Desktop\IA\123', '-print_format', 'json', '-show_format', '-show_streams']' returned non-zero exit status 1.

**Comment by klauz996** [comment]
el -d cpu es al final del todo

**Comment by Gringo541** [comment]
cuando le pongo el -d cpu al final me dice que no encuentra el archivo, si se lo borro al -d, me dice el mismo error del principio... ya no se que hacer

**Comment by Gringo541** [comment]
ya lo pude solucionar, para los que le pase lo mismo usen el siguiente comando
python.exe -m demucs.separate -o ( .\(Directorio)\Salida -n demucs -d cpu .\(Directorio).(extencion del archivo de musica )
