### ISSUE TITLE
Output files are not saved

### ISSUE THREAD

**Issue by ProgressiveProgression** [facebookresearch/demucs#415]
## 🐛 Bug Report

Output files are not saved due to unexpected keyword "argument"

## To Reproduce

Run `demucs -n htdemucs_ft "PATH"`

## Expected behavior

Output files should be saved

## Actual Behavior
```

Traceback (most recent call last):
  File "c:\users\elbit\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\elbit\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\elbit\anaconda3\Scripts\demucs.exe\__main__.py", line 7, in <module>
  File "c:\users\elbit\anaconda3\lib\site-packages\demucs\separate.py", line 185, in main
    save_audio(source, str(stem), **kwargs)
  File "c:\users\elbit\anaconda3\lib\site-packages\demucs\audio.py", line 254, in save_audio
    ta.save(str(path), wav, sample_rate=samplerate,
TypeError: save() got an unexpected keyword argument 'encoding'
```

## Your Environment

- Python and PyTorch version: Python 3.8.0 Pytorch '1.11.0+cpu'
- Operating system and version (desktop or mobile): Windows 10 desktop
- Hardware (gpu or cpu, amount of RAM etc.): 

Intel Core i7-4900MQ 2.80 Ghz
RAM 32 GB DDR3
Nvidia Quadro K3100M

**Comment by CarlGao4** [comment]
Please run `python -c "import soundfile;print(soundfile.__version__);print(soundfile.__libsndfile_version__)"` and paste the outputs here.

**Comment by ProgressiveProgression** [comment]
The output is:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'soundfile'
```

**Comment by CarlGao4** [comment]
Then run `pip install soundfile`

**Comment by UnitedShoes** [comment]
Hello,

New to github. I'm also getting this issue.

`Traceback (most recent call last):
  File "C:\Users\Kyle\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Kyle\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kyle\anaconda3\Scripts\demucs.exe\__main__.py", line 7, in <module>
  File "C:\Users\Kyle\anaconda3\lib\site-packages\demucs\separate.py", line 192, in main
    save_audio(sources.pop(model.sources.index(args.stem)), str(stem), **kwargs)
  File "C:\Users\Kyle\anaconda3\lib\site-packages\demucs\audio.py", line 254, in save_audio
    ta.save(str(path), wav, sample_rate=samplerate,
TypeError: save() got an unexpected keyword argument 'encoding'`

The soundfile version test posted above returns versions `0.11.0, 1.1.0`. I ran the pip install for it as well to make sure it's updated.

**Comment by CarlGao4** [comment]
Then what is the version of torch? 
`python -c "import torch;print(torch.__version__)`

**Comment by UnitedShoes** [comment]
> Then what is the version of torch? `python -c "import torch;print(torch.__version__)`

Thanks for the response, the returned version of torch is `1.13.1+cpu`.

**Comment by CarlGao4** [comment]
Installing ffmpeg manually does not influence this. I think the problem is that your input file has wrong format. Can you try converting it into wav?

**Comment by AARP41298** [comment]
> Then run `pip install soundfile`

this work for me

**Comment by PlaidDroid** [comment]
> Then run `pip install soundfile`

thanks. worked for me

**Comment by Tomissugo** [comment]
Thanks, worked for me too !
