### ISSUE TITLE
OSError: [WinError 126]

### ISSUE THREAD

**Issue by aureyoboss** [facebookresearch/demucs#423]
## 🐛 Bug Report

_OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\PC\anaconda3\lib\site-packages\torch\lib\shm.dll" or one of its dependencies._

## To Reproduce

1. Step 1 : Install **Anaconda3-2022.10-Windows-x86_64.exe** (and restart computer).
1. Step 2 : Start the **Anaconda prompt** (without administrator rights).
1. Step 3 : I follow the designated instructions [here](https://github.com/facebookresearch/demucs/blob/main/docs/windows.md).
2. Step 4 : Run: `conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia`
3. Step 5 : Run: `conda install -c conda-forge ffmpeg`
4. Step 6 : Run: `python.exe -m pip install -U demucs PySoundFile`
5. Step 7 : Run: `demucs -n htdemucs_ft --two-stems=vocals --out="D:\Songs\Demucs" "D:\Songs\BestSong.mp3"`

## Expected behavior

I was hoping to be able to use Demucs with CUDA.

## Actual Behavior

```
(base) C:\Users\PC>demucs -n htdemucs_ft --two-stems=vocals --out="D:\Songs\Demucs" "D:\Songs\BestSong.mp3"
Traceback (most recent call last):
  File "C:\Users\PC\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\PC\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\PC\anaconda3\Scripts\demucs.exe\__main__.py", line 4, in <module>
  File "C:\Users\PC\anaconda3\lib\site-packages\demucs\separate.py", line 12, in <module>
    from dora.log import fatal
  File "C:\Users\PC\anaconda3\lib\site-packages\dora\__init__.py", line 66, in <module>
    from .explore import Explorer, Launcher
  File "C:\Users\PC\anaconda3\lib\site-packages\dora\explore.py", line 27, in <module>
    from .shep import Shepherd, Sheep
  File "C:\Users\PC\anaconda3\lib\site-packages\dora\shep.py", line 25, in <module>
    from .distrib import get_distrib_spec
  File "C:\Users\PC\anaconda3\lib\site-packages\dora\distrib.py", line 14, in <module>
    import torch
  File "C:\Users\PC\anaconda3\lib\site-packages\torch\__init__.py", line 139, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\PC\anaconda3\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
```

## Your Environment

- Python and PyTorch version: Python 3.9.13. PyTorch 1.13.0.
- Operating system and version (desktop or mobile): Desktop - Windows 11 Home 22H2 (22621.900).
- Hardware (gpu or cpu, amount of RAM etc.): NVIDIA GeForce RTX 3060 (12Go). 16Go of RAM / 16Go Swap File. Intel Core i5-12400F.

**Comment by CarlGao4** [comment]
Can you find the file `C:\Users\PC\anaconda3\lib\site-packages\torch\lib\shm.dll` in your file explorer?

**Comment by aureyoboss** [comment]
> Can you find the file `C:\Users\PC\anaconda3\lib\site-packages\torch\lib\shm.dll` in your file explorer?

No.

I restarted the whole installation procedure 5 times yesterday. By uninstalling Anaconda each time and deleting the directories (.cache and .conda) in C:\Users\PC.
I even tested using administrator rights to: `conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia`

I was wondering if we shouldn't install the Cuda SDK before (https://developer.nvidia.com/cuda-downloads)?

**Comment by CarlGao4** [comment]
Maybe you can try installing it with pip? Or use miniconda instead of anaconda? 
Installing with pip: Just create a virtual environment (recommended, but you can skip this) and install ffmpeg using conda. Then follow [the guides here](https://pytorch.org/get-started/locally/) to install torch. And install demucs.

**Comment by aureyoboss** [comment]
> Maybe you can try installing it with pip? Or use miniconda instead of anaconda? Installing with pip: Just create a virtual environment (recommended, but you can skip this) and install ffmpeg using conda. Then follow [the guides here](https://pytorch.org/get-started/locally/) to install torch. And install demucs.

It worked ! You are awesome !
Thanks a lot.

**Comment by CarlGao4** [comment]
Then you can close this issue.

**Comment by BaoBlack** [comment]
> Maybe you can try installing it with pip? Or use miniconda instead of anaconda? Installing with pip: Just create a virtual environment (recommended, but you can skip this) and install ffmpeg using conda. Then follow [the guides here](https://pytorch.org/get-started/locally/) to install torch. And install demucs.

Can you please guide me in detail how to install as you mentioned?

**Comment by BaoBlack** [comment]
> > Maybe you can try installing it with pip? Or use miniconda instead of anaconda? Installing with pip: Just create a virtual environment (recommended, but you can skip this) and install ffmpeg using conda. Then follow [the guides here](https://pytorch.org/get-started/locally/) to install torch. And install demucs.
> 
> It worked ! You are awesome ! Thanks a lot.

Can you please guide me on how to install to fix this problem? Please
