### ISSUE TITLE
I can no longer launch demuc

### ISSUE THREAD

**Issue by GUUser91** [facebookresearch/demucs#440]
I get this error message. I'm using the bleeding edge version. I installed omegaconf with pip install omegaconf command and sudo pacman -S python-omegaconf 
> $ demucs --two-stems=vocals '1 3.wav'

> Traceback (most recent call last):

  File "/home/user/.local/bin/demucs", line 5, in <module>
    from demucs.separate import main
  File "/home/user/.local/lib/python3.10/site-packages/demucs/separate.py", line 12, in <module>
    from dora.log import fatal
  File "/home/user/.local/lib/python3.10/site-packages/dora/__init__.py", line 66, in <module>
    from .explore import Explorer, Launcher
  File "/home/user/.local/lib/python3.10/site-packages/dora/explore.py", line 27, in <module>
    from .shep import Shepherd, Sheep
  File "/home/user/.local/lib/python3.10/site-packages/dora/shep.py", line 23, in <module>
    from . import git_save
  File "/home/user/.local/lib/python3.10/site-packages/dora/git_save.py", line 16, in <module>
    from .main import DecoratedMain
  File "/home/user/.local/lib/python3.10/site-packages/dora/main.py", line 25, in <module>
    from .names import NamesMixin
  File "/home/user/.local/lib/python3.10/site-packages/dora/names.py", line 11, in <module>
    from .xp import XP
  File "/home/user/.local/lib/python3.10/site-packages/dora/xp.py", line 15, in <module>
    from .link import Link
  File "/home/user/.local/lib/python3.10/site-packages/dora/link.py", line 13, in <module>
    from . import utils
  File "/home/user/.local/lib/python3.10/site-packages/dora/utils.py", line 18, in <module>
    from omegaconf.basecontainer import BaseContainer
ModuleNotFoundError: No module named 'omegaconf.basecontainer'

**Comment by GUUser91** [comment]
Nevermind, I uninstalled python and deleted all the python folders in the lib directory and did a clean install. It works now.
