### ISSUE TITLE
FileNotFoundError when attempting to upgrade demucs on Windows

### ISSUE THREAD

**Issue by Klambyyy** [facebookresearch/demucs#449]
Running Windows 10 Pro.
Output of Anaconda prompt below. 
```

(base) C:\Users\Chris>conda install -c conda-forge ffmpeg
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.1.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: E:\Users\Klambyyy\Software\Anaconda

  added / updated specs:
    - ffmpeg


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-23.1.0               |   py39hcbf5309_0         912 KB  conda-forge
    ffmpeg-4.3.1               |       ha925a31_0        26.2 MB  conda-forge
    python_abi-3.9             |           2_cp39           4 KB  conda-forge
    ruamel.yaml-0.17.21        |   py39hb82d6ee_1         169 KB  conda-forge
    ruamel.yaml.clib-0.2.6     |   py39h2bbff1b_1         101 KB
    ------------------------------------------------------------
                                           Total:        27.3 MB

The following NEW packages will be INSTALLED:

  ffmpeg             conda-forge/win-64::ffmpeg-4.3.1-ha925a31_0 None
  python_abi         conda-forge/win-64::python_abi-3.9-2_cp39 None
  ruamel.yaml        conda-forge/win-64::ruamel.yaml-0.17.21-py39hb82d6ee_1 None
  ruamel.yaml.clib   pkgs/main/win-64::ruamel.yaml.clib-0.2.6-py39h2bbff1b_1 None

The following packages will be UPDATED:

  conda              pkgs/main::conda-22.9.0-py39haa95532_0 --> conda-forge::conda-23.1.0-py39hcbf5309_0 None


Proceed ([y]/n)? y


Downloading and Extracting Packages
ruamel.yaml.clib-0.2 | 101 KB    | ############################################################################ | 100%
ffmpeg-4.3.1         | 26.2 MB   | ############################################################################ | 100%
ruamel.yaml-0.17.21  | 169 KB    | ################################################################################################################# | 100%
python_abi-3.9       | 4 KB      | ################################################################################################################# | 100%
conda-23.1.0         | 912 KB    | ################################################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done

(base) C:\Users\Klambyyy>C:\Users\Klambyyy\AppData\Local\Programs\Python\Python311\python.exe -m pip install -U demucs PySoundFile
WARNING: Skipping C:\Users\Klambyyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline-2.1-py3.11-win-amd64.egg/pyreadline-2.1-py3.4.egg-info due to invalid metadata entry 'name'
Collecting demucs
  Downloading demucs-4.0.0.tar.gz (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting PySoundFile
  Downloading PySoundFile-0.9.0.post1-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33-none-win_amd64.whl (671 kB)
     ---------------------------------------- 671.8/671.8 kB 7.1 MB/s eta 0:00:00
Collecting dora-search
  Downloading dora_search-0.1.11.tar.gz (87 kB)
     ---------------------------------------- 87.0/87.0 kB 2.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting diffq>=0.2.1
  Downloading diffq-0.2.3.tar.gz (46 kB)
     ---------------------------------------- 46.3/46.3 kB 2.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting einops
  Downloading einops-0.6.0-py3-none-any.whl (41 kB)
     ---------------------------------------- 41.6/41.6 kB 2.1 MB/s eta 0:00:00
Collecting julius>=0.2.3
  Downloading julius-0.2.7.tar.gz (59 kB)
     ---------------------------------------- 59.6/59.6 kB 1.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting lameenc>=1.2
  Downloading lameenc-1.4.2-cp311-cp311-win_amd64.whl (158 kB)
     ---------------------------------------- 158.2/158.2 kB 3.1 MB/s eta 0:00:00
Collecting openunmix
  Downloading openunmix-1.2.1-py3-none-any.whl (46 kB)
     ---------------------------------------- 46.7/46.7 kB 2.4 MB/s eta 0:00:00
Collecting pyyaml
  Downloading PyYAML-6.0-cp311-cp311-win_amd64.whl (143 kB)
     ---------------------------------------- 143.2/143.2 kB 4.3 MB/s eta 0:00:00
Collecting demucs
  Downloading demucs-3.0.6.tar.gz (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading demucs-3.0.5.tar.gz (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 5.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading demucs-3.0.4.tar.gz (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 5.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading demucs-3.0.3.tar.gz (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 4.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading demucs-3.0.2.tar.gz (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 5.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading demucs-3.0.1.tar.gz (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 4.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading demucs-3.0.0.tar.gz (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Klambyyy\AppData\Local\Temp\pip-install-leqd17kx\demucs_8a578d4da7724e3ba42f41a623b2a7d9\setup.py", line 39, in <module>
          REQUIRED = load_requirements('requirements_minimal.txt')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Klambyyy\AppData\Local\Temp\pip-install-leqd17kx\demucs_8a578d4da7724e3ba42f41a623b2a7d9\setup.py", line 34, in load_requirements
          required = [i.strip() for i in open(HERE / name)]
                                         ^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Klambyyy\\AppData\\Local\\Temp\\pip-install-leqd17kx\\demucs_8a578d4da7724e3ba42f41a623b2a7d9\\requirements_minimal.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\Klambyyy\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip

(base) C:\Users\Klambyyy>C:\Users\Klambyyy\AppData\Local\Programs\Python\Python311\python.exe -m pip install -U --upgrade pip
WARNING: Skipping C:\Users\Klambyyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline-2.1-py3.11-win-amd64.egg/pyreadline-2.1-py3.4.egg-info due to invalid metadata entry 'name'
Requirement already satisfied: pip in c:\users\Klambyyy\appdata\local\programs\python\python311\lib\site-packages (22.3.1)
Collecting pip
  Downloading pip-23.0.1-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 2.4 MB/s eta 0:00:00
WARNING: Skipping C:\Users\Klambyyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline-2.1-py3.11-win-amd64.egg/pyreadline-2.1-py3.4.egg-info due to invalid metadata entry 'name'
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
  WARNING: The scripts pip.exe, pip3.11.exe and pip3.exe are installed in 'C:\Users\Klambyyy\AppData\Local\Programs\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-23.0.1

(base) C:\Users\Klambyyy>C:\Users\Klambyyy\AppData\Local\Programs\Python\Python311\python.exe -m pip install -U demucs
WARNING: Skipping C:\Users\Klambyyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline-2.1-py3.11-win-amd64.egg/pyreadline-2.1-py3.4.egg-info due to invalid metadata entry 'name'
Collecting demucs
  Using cached demucs-4.0.0.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
Collecting dora-search
  Using cached dora_search-0.1.11.tar.gz (87 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting diffq>=0.2.1
  Using cached diffq-0.2.3.tar.gz (46 kB)
  Preparing metadata (setup.py) ... done
Collecting einops
  Using cached einops-0.6.0-py3-none-any.whl (41 kB)
Collecting julius>=0.2.3
  Using cached julius-0.2.7.tar.gz (59 kB)
  Preparing metadata (setup.py) ... done
Collecting lameenc>=1.2
  Using cached lameenc-1.4.2-cp311-cp311-win_amd64.whl (158 kB)
Collecting openunmix
  Using cached openunmix-1.2.1-py3-none-any.whl (46 kB)
Collecting pyyaml
  Using cached PyYAML-6.0-cp311-cp311-win_amd64.whl (143 kB)
Collecting demucs
  Using cached demucs-3.0.6.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-3.0.5.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-3.0.4.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-3.0.3.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-3.0.2.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-3.0.1.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-3.0.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Klambyyy\AppData\Local\Temp\pip-install-wa363bys\demucs_8a46c912c1b8468d9f120dc37838e8d1\setup.py", line 39, in <module>
          REQUIRED = load_requirements('requirements_minimal.txt')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Klambyyy\AppData\Local\Temp\pip-install-wa363bys\demucs_8a46c912c1b8468d9f120dc37838e8d1\setup.py", line 34, in load_requirements
          required = [i.strip() for i in open(HERE / name)]
                                         ^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Klambyyy\\AppData\\Local\\Temp\\pip-install-wa363bys\\demucs_8a46c912c1b8468d9f120dc37838e8d1\\requirements_minimal.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(base) C:\Users\Klambyyy>C:\Users\Klambyyy\AppData\Local\Programs\Python\Python311\python.exe -m pip install -U demucs
WARNING: Skipping C:\Users\Klambyyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline-2.1-py3.11-win-amd64.egg/pyreadline-2.1-py3.4.egg-info due to invalid metadata entry 'name'
Collecting demucs
  Using cached demucs-4.0.0.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
Collecting dora-search
  Using cached dora_search-0.1.11.tar.gz (87 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting diffq>=0.2.1
  Using cached diffq-0.2.3.tar.gz (46 kB)
  Preparing metadata (setup.py) ... done
Collecting einops
  Using cached einops-0.6.0-py3-none-any.whl (41 kB)
Collecting julius>=0.2.3
  Using cached julius-0.2.7.tar.gz (59 kB)
  Preparing metadata (setup.py) ... done
Collecting lameenc>=1.2
  Using cached lameenc-1.4.2-cp311-cp311-win_amd64.whl (158 kB)
Collecting openunmix
  Using cached openunmix-1.2.1-py3-none-any.whl (46 kB)
Collecting pyyaml
  Using cached PyYAML-6.0-cp311-cp311-win_amd64.whl (143 kB)
Collecting demucs
  Using cached demucs-3.0.6.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-3.0.5.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-3.0.4.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-3.0.3.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-3.0.2.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-3.0.1.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
  Using cached demucs-3.0.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Klambyyy\AppData\Local\Temp\pip-install-w_id7ck9\demucs_96402eaa85f94056a5ba92bc9e68ecd3\setup.py", line 39, in <module>
          REQUIRED = load_requirements('requirements_minimal.txt')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Klambyyy\AppData\Local\Temp\pip-install-w_id7ck9\demucs_96402eaa85f94056a5ba92bc9e68ecd3\setup.py", line 34, in load_requirements
          required = [i.strip() for i in open(HERE / name)]
                                         ^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Klambyyy\\AppData\\Local\\Temp\\pip-install-w_id7ck9\\demucs_96402eaa85f94056a5ba92bc9e68ecd3\\requirements_minimal.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(base) C:\Users\Klambyyy>
```

**Comment by CarlGao4** [comment]
It's quite interesting that pip falled back to demucs 3.0.0
But I have no idea about how to solve this at this moment
