### ISSUE TITLE
subprocess.CalledProcessError: Command ' ' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by ResilleTV** [facebookresearch/demucs#51]
Hola, no entiendo nada de esto, solo quiero aprender a ocupar esta cosa para separar pistas, no soy programador ni nada, instalé todo según las instrucciones, intenté poniendo la ruta del archivo entre comillas, cambiándolo de lugar y me arroja este error :( 

(demucs) C:\Users\thero\demucs>python.exe -m demucs.separate --dl "C:\Users\thero\Documents\DAY6_1.mp3"
  0%|                                                                                            | 0/1 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\thero\Anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\thero\Anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\thero\demucs\demucs\separate.py", line 143, in <module>
    main()
  File "C:\Users\thero\demucs\demucs\separate.py", line 127, in main
    wav = AudioFile(track).read(streams=0, samplerate=44100, channels=2).to(args.device)
  File "C:\Users\thero\demucs\demucs\audio.py", line 98, in read
    streams = np.array(range(len(self)))[streams]
  File "C:\Users\thero\demucs\demucs\audio.py", line 59, in __len__
    return len(self._audio_streams)
  File "C:\Users\thero\demucs\demucs\audio.py", line 54, in _audio_streams
    index for index, stream in enumerate(self.info["streams"])
  File "C:\Users\thero\demucs\demucs\audio.py", line 44, in info
    self._info = _read_info(self.path)
  File "C:\Users\thero\demucs\demucs\audio.py", line 19, in _read_info
    str(path), '-print_format', 'json', '-show_format', '-show_streams'
  File "C:\Users\thero\Anaconda3\envs\demucs\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Users\thero\Anaconda3\envs\demucs\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ffprobe', '-loglevel', 'panic', 'C:\\Users\\thero\\Documents\\DAY6_1.mp3', '-print_format', 'json', '-show_format', '-show_streams']' returned non-zero exit status 1.

**Comment by rokimoki** [comment]
¿Se te ha descargado la red entrenada de 2,5gb? ¿tienes espacio para descargarla? no veo una lógica en el error. ¿Puedes pasar pantallazo? ¿Qué comandos has ejecutado previamente?

**Comment by adefossez** [comment]
Hey @ResilleTV  , can you run `ffprobe C:\Users\thero\Documents\DAY6_1.mp3` and tell me what it does?

**Comment by adefossez** [comment]
Related issues
https://github.com/facebookresearch/demucs/issues/64
https://github.com/facebookresearch/demucs/issues/65

**Comment by Kingo310** [comment]
> Hola @ResilleTV , ¿puedes correr `ffprobe C:\Users\thero\Documents\DAY6_1.mp3`y decirme qué hace?

This is what comes out!!!!


![Captura](https://user-images.githubusercontent.com/61298702/74991210-efee4f00-540a-11ea-8f97-99270882e02a.PNG)

**Comment by adefossez** [comment]
Hey, sorry for not replying before, you must put quotes `'` around the filenames if they contain spaces :)
