### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by huairen99** [facebookresearch/demucs#527]
## ❓ Questions

(Please ask your question here.)
(demucs) D:\data\cqZhang\demucs-3>dora run -d -f 81de367c
Parser Injecting argv ['hdemucs.norm_starts=999', 'hdemucs.cac=False', 'test.split=True', 'valid_apply=True', 'model=hdemucs', 'hdemucs.dconv_lstm=4', 'ema.epoch=[0.9, 0.95]', 'ema.batch=[0.9995, 0.9999]', 'seed=42', 'hdemucs.hybrid_old=True', 'svd=base', 'svd.penalty=1e-05', 'svd.dim=100', 'svd.convtr=True', 'optim.lr=0.0005'] from sig 81de367c
Executor: Starting 1 worker processes for DDP.
D:\app\anaconda\envs\demucs\lib\site-packages\hydra\_internal\hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[07-16 15:21:53][demucs.train][INFO] - For logs, checkpoints and samples check D:\data\cqZhang\demucs-3\outputs\xps\81de367c
[07-16 15:21:53][dora.distrib][INFO] - world_size is 1, skipping init.
[07-16 15:21:57][demucs.train][INFO] - train/valid set size: 18368 14
[07-16 15:21:58][demucs.solver][INFO] - ----------------------------------------------------------------------
[07-16 15:21:58][demucs.solver][INFO] - Training...
Error executing job with overrides: ['hdemucs.norm_starts=999', 'hdemucs.cac=False', 'test.split=True', 'valid_apply=True', 'model=hdemucs', 'hdemucs.dconv_lstm=4', 'ema.epoch=[0.9, 0.95]', 'ema.batch=[0.9995, 0.9999]', 'seed=42', 'hdemucs.hybrid_old=True', 'svd=base', 'svd.penalty=1e-05', 'svd.dim=100', 'svd.convtr=True', 'optim.lr=0.0005']
Traceback (most recent call last):
  File "D:\data\cqZhang\demucs-3\demucs\train.py", line 148, in main
    solver.train()
  File "D:\data\cqZhang\demucs-3\demucs\solver.py", line 195, in train
    metrics['train'] = self._run_one_epoch(epoch)
  File "D:\data\cqZhang\demucs-3\demucs\solver.py", line 305, in _run_one_epoch
    for idx, sources in enumerate(logprog):
  File "D:\app\anaconda\envs\demucs\lib\site-packages\dora\log.py", line 70, in __next__
    value = next(self._iterator)
  File "D:\app\anaconda\envs\demucs\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "D:\app\anaconda\envs\demucs\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "D:\app\anaconda\envs\demucs\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "D:\app\anaconda\envs\demucs\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\app\anaconda\envs\demucs\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\app\anaconda\envs\demucs\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\app\anaconda\envs\demucs\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\data\cqZhang\demucs-3\demucs\repitch.py", line 47, in __getitem__
    stream = repitch(
  File "D:\data\cqZhang\demucs-3\demucs\repitch.py", line 81, in repitch
    sp.run(command, capture_output=True, check=True)
  File "D:\app\anaconda\envs\demucs\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\app\anaconda\envs\demucs\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\app\anaconda\envs\demucs\lib\subprocess.py", line 1327, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Executor: Worker 0 died, killing all workers

====================================================================
The error message is shown above. What should I do?

**Comment by adefossez** [comment]
you probably don't have soundstretch installed. see https://github.com/facebookresearch/demucs/tree/main#for-machine-learning-scientists
