### ISSUE TITLE
Input size and kernel size mismatch

### ISSUE THREAD

**Issue by tsushimiikado** [facebookresearch/demucs#53]
hi i'm new in this site and have this error:
(demucs) C:\Users\anime\demucs>python.exe -m demucs.separate --dl "C:\Users\anime\Music\spotify\ED Evangelion.mp3"
Separated tracks will be stored in C:\Users\anime\demucs\separated\demucs
Separating track C:\Users\anime\Music\spotify\ED Evangelion.mp3
 96%|████████████████████████████████████████████████████████████████████████████████████████████▌   | 270/280 [09:02<00:19,  1.98s/seconds]Traceback (most recent call last):
  File "C:\Users\anime\Anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\anime\Anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\anime\demucs\demucs\separate.py", line 146, in <module>
    main()
  File "C:\Users\anime\demucs\demucs\separate.py", line 135, in main
    sources = apply_model(model, wav, shifts=args.shifts, split=args.split, progress=True)
  File "C:\Users\anime\demucs\demucs\utils.py", line 117, in apply_model
    chunk_out = apply_model(model, chunk, shifts=shifts)
  File "C:\Users\anime\demucs\demucs\utils.py", line 138, in apply_model
    out = model(padded.unsqueeze(0))[0]
  File "C:\Users\anime\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\anime\demucs\demucs\model.py", line 207, in forward
    x = decode(x)
  File "C:\Users\anime\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\anime\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\anime\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\anime\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\conv.py", line 202, in forward
    self.padding, self.dilation, self.groups)
### RuntimeError: Calculated padded input size per channel: (2). Kernel size: (3). Kernel size can't be greater than actual input  size
 96%|████████████████████████████████████████████████████████████████████████████████████████████▌   | 270/280 [09:03<00:20,  2.01s/seconds]

how i can fix it?
THX

**Comment by adefossez** [comment]
Hey @tsushimiikado , sorry for my late reply. Could you share the mp3 with me so that I can debug this? You can send it by email to `defossez@fb.com`.

**Comment by adefossez** [comment]
@tsushimiikado , it should be fixed now :)
