### ISSUE TITLE
problem when importing lamenc: undefined symbol __pow_finite

### ISSUE THREAD

**Issue by rlyacht** [facebookresearch/demucs#537]
## 🐛 Bug Report

When run under Ubuntu 23,04 I get an error when lameenc is imported by demucs.  I put a full traceback below.  The issue is

```lameenc.cpython-310-x86_64-linux-gnu.so: undefined symbol: __pow_finite```

I've found [some mentions of this online](https://stackoverflow.com/questions/62334452/fast-math-cause-undefined-reference-to-pow-finite), and tried recompiling libmp3lame with -fno-finite-math-only, but that didn't fix it.

This may well be lameenc's problem, not yours. 

## To Reproduce

1. Build with ./configure and make
2. Create new python 3.10 venv and activate
3. pip3 install -U demucs
4. demucs audiofile.mp3

## Expected behavior

demucs would run and  create  out a set of audio files

## Actual Behavior

```
py310-demucs) (base) robt@nucnix7:~/src/demucs$ demucs -help
Traceback (most recent call last):
  File "/home/robt/envs/py310-demucs/bin/demucs", line 33, in <module>
    sys.exit(load_entry_point('demucs==4.0.0', 'console_scripts', 'demucs')())
  File "/home/robt/envs/py310-demucs/bin/demucs", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/robt/anaconda3/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/robt/anaconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/robt/envs/py310-demucs/lib/python3.10/site-packages/demucs/separate.py", line 17, in <module>
    from .audio import AudioFile, convert_audio, save_audio
  File "/home/robt/envs/py310-demucs/lib/python3.10/site-packages/demucs/audio.py", line 10, in <module>
    import lameenc
ImportError: /home/robt/envs/py310-demucs/lib/python3.10/site-packages/lameenc.cpython-310-x86_64-linux-gnu.so: undefined symbol: __pow_finite

```

Just importing  lameenc directly, I get this:
```
>> import lameenc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/robt/envs/py310-demucs/lib/python3.10/site-packages/lameenc.cpython-310-x86_64-linux-gnu.so: undefined symbol: __pow_finite
```

## Your Environment

demucs 4.0.0
Ubuntu 23.04
python 3.10
torch 2.0.1+cu117
Intel NUC7i7BNH: i7-7567U,  16G RAM, no GPU

**Comment by CarlGao4** [comment]
I think this is an issue of lameenc, but not demucs. You can open an issue under https://github.com/chrisstaite/lameenc

**Comment by CarlGao4** [comment]
As you can see in https://github.com/chrisstaite/lameenc/issues/22 , the developer of lameenc has just fixed it. You can try updating lameenc

**Comment by rlyacht** [comment]
Thank you Weiqi.  I'm looking forward to trying demucs.
