### ISSUE TITLE
Permission denied: '/data/models/hub' during make run track=[song]

### ISSUE THREAD

**Issue by arjantenhoopen** [facebookresearch/demucs#543]
## 🐛 Bug Report

Get Permission Denied: /data/models/hub after running **make run track=YouShouldBeDancing.flac**

## To Reproduce

Run the command (as a normal user) again and again and again ....

```
arjan@arjanpc:/tenhoopen/git/demucs> make run track=YouShouldBeDancing.flac
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  96.25MB
Step 1/13 : FROM nvidia/cuda:11.8.0-base-ubuntu22.04
 ---> b63f93532b2a
Step 2/13 : USER root
 ---> Using cache
 ---> d3c535f24ec6
Step 3/13 : ENV TORCH_HOME=/data/models
 ---> Using cache
 ---> b8f75fc75471
Step 4/13 : RUN apt update && apt install -y --no-install-recommends     build-essential     ffmpeg     git     python3     python3-dev     python3-pip     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 2d48406f0a82
Step 5/13 : RUN git clone -b main --single-branch https://github.com/facebookresearch/demucs /lib/demucs
 ---> Using cache
 ---> 5b001c60df2f
Step 6/13 : WORKDIR /lib/demucs
 ---> Using cache
 ---> 8c1617e8a5e8
Step 7/13 : RUN python3 -m pip install -e . --no-cache-dir
 ---> Using cache
 ---> cb710d7c328d
Step 8/13 : RUN python3 -m demucs -d cpu test.mp3
 ---> Using cache
 ---> 9b238985fd42
Step 9/13 : RUN rm -r separated
 ---> Using cache
 ---> dfa7a127124b
Step 10/13 : VOLUME /data/input
 ---> Using cache
 ---> b238b385f54f
Step 11/13 : VOLUME /data/output
 ---> Using cache
 ---> df8b83dbdfd8
Step 12/13 : VOLUME /data/models
 ---> Using cache
 ---> c6e0c979bb46
Step 13/13 : ENTRYPOINT ["/bin/bash", "--login", "-c"]
 ---> Using cache
 ---> ea606678c70a
Successfully built ea606678c70a
Successfully tagged xserrat/facebook-demucs:latest
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/demucs/demucs/__main__.py", line 10, in <module>
    main()
  File "/usr/lib/demucs/demucs/separate.py", line 133, in main
    model = get_model_from_args(args)
  File "/usr/lib/demucs/demucs/pretrained.py", line 96, in get_model_from_args
    return get_model(name=args.name, repo=args.repo)
  File "/usr/lib/demucs/demucs/pretrained.py", line 76, in get_model
    model = any_repo.get_model(name)
  File "/usr/lib/demucs/demucs/repo.py", line 148, in get_model
    return self.bag_repo.get_model(name_or_sig)
  File "/usr/lib/demucs/demucs/repo.py", line 130, in get_model
    models = [self.model_repo.get_model(sig) for sig in signatures]
  File "/usr/lib/demucs/demucs/repo.py", line 130, in <listcomp>
    models = [self.model_repo.get_model(sig) for sig in signatures]
  File "/usr/lib/demucs/demucs/repo.py", line 65, in get_model
    pkg = torch.hub.load_state_dict_from_url(
  File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 726, in load_state_dict_from_url
    os.makedirs(model_dir)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data/models/hub'
make: *** [Makefile:32: run] Fout 1
arjan@arjanpc:/tenhoopen/git/demucs>
```

## Your Environment
```
arjan@arjanpc:/tenhoopen/git/demucs> cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.5"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
arjan@arjanpc:/tenhoopen/git/demucs> 
```

```
arjan@arjanpc:/tenhoopen/git/demucs> docker --version
Docker version 23.0.6-ce, build 9dbdbd4b6d76
arjan@arjanpc:/tenhoopen/git/demucs> 
```

```
arjan@arjanpc:/tenhoopen/git/demucs> make --version
GNU Make 4.2.1
Dit programma is gecompileerd voor x86_64-suse-linux-gnu.
Copyright (C) 1988-2016 Free Software Foundation, Inc.
Licentie GPLv3+: GNU GPL versie 3 of nieuwer <http://gnu.org/licenses/gpl.html>
Dit is vrije software: u mag het vrijelijk wijzigen en verder verspreiden.
Er is GEEN GARANTIE, voor zover de wet dit toestaat.
arjan@arjanpc:/tenhoopen/git/demucs>
```

**Comment by CarlGao4** [comment]
Maybe you can try using `sudo`?

**Comment by arjantenhoopen** [comment]
Sorry, same result:

arjan@arjanpc:/tenhoopen/git/demucs> sudo make run track=YouShouldBeDancing.flac
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  96.25MB
Step 1/13 : FROM nvidia/cuda:11.8.0-base-ubuntu22.04
 ---> b63f93532b2a
Step 2/13 : USER root
 ---> Using cache
 ---> d3c535f24ec6
Step 3/13 : ENV TORCH_HOME=/data/models
 ---> Using cache
 ---> b8f75fc75471
Step 4/13 : RUN apt update && apt install -y --no-install-recommends     build-essential     ffmpeg     git     python3     python3-dev     python3-pip     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 2d48406f0a82
Step 5/13 : RUN git clone -b main --single-branch https://github.com/facebookresearch/demucs /lib/demucs
 ---> Using cache
 ---> 5b001c60df2f
Step 6/13 : WORKDIR /lib/demucs
 ---> Using cache
 ---> 8c1617e8a5e8
Step 7/13 : RUN python3 -m pip install -e . --no-cache-dir
 ---> Using cache
 ---> cb710d7c328d
Step 8/13 : RUN python3 -m demucs -d cpu test.mp3
 ---> Using cache
 ---> 9b238985fd42
Step 9/13 : RUN rm -r separated
 ---> Using cache
 ---> dfa7a127124b
Step 10/13 : VOLUME /data/input
 ---> Using cache
 ---> b238b385f54f
Step 11/13 : VOLUME /data/output
 ---> Using cache
 ---> df8b83dbdfd8
Step 12/13 : VOLUME /data/models
 ---> Using cache
 ---> c6e0c979bb46
Step 13/13 : ENTRYPOINT ["/bin/bash", "--login", "-c"]
 ---> Using cache
 ---> ea606678c70a
Successfully built ea606678c70a
Successfully tagged xserrat/facebook-demucs:latest
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/demucs/demucs/__main__.py", line 10, in <module>
    main()
  File "/usr/lib/demucs/demucs/separate.py", line 133, in main
    model = get_model_from_args(args)
  File "/usr/lib/demucs/demucs/pretrained.py", line 96, in get_model_from_args
    return get_model(name=args.name, repo=args.repo)
  File "/usr/lib/demucs/demucs/pretrained.py", line 76, in get_model
    model = any_repo.get_model(name)
  File "/usr/lib/demucs/demucs/repo.py", line 148, in get_model
    return self.bag_repo.get_model(name_or_sig)
  File "/usr/lib/demucs/demucs/repo.py", line 130, in get_model
    models = [self.model_repo.get_model(sig) for sig in signatures]
  File "/usr/lib/demucs/demucs/repo.py", line 130, in <listcomp>
    models = [self.model_repo.get_model(sig) for sig in signatures]
  File "/usr/lib/demucs/demucs/repo.py", line 65, in get_model
    pkg = torch.hub.load_state_dict_from_url(
  File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 726, in load_state_dict_from_url
    os.makedirs(model_dir)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
**PermissionError: [Errno 13] Permission denied: '/data/models/hub'**
make: *** [Makefile:32: run] Fout 1
arjan@arjanpc:/tenhoopen/git/demucs>`
