### ISSUE TITLE
[WinError 2] The system cannot find the specified file with demucs V2 

### ISSUE THREAD

**Issue by HaruChanuwu** [facebookresearch/demucs#549]
I cannot perform training on demucs V2, I have downloaded the MUSDB database but I get the following error when trying to perform the training:
[WinError 2] The system cannot find the specified file

I already tried deleting "metadata" but it still doesn't work.

I would appreciate your kind responses.

ERROR:
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
(demucs) C:\Users\USER\demucs2>python.exe -m demucs -b 4 --musdb "C:\Users\USER\musdb"
Experiment musdb=musdb batch_size=4
Agumentation pipeline: Sequential(
  (0): Shift()
  (1): FlipSign()
  (2): FlipChannels()
  (3): Scale()
  (4): Remix()
)
Number of training samples adjusted to 447146
Train set and valid set sizes 18124 14
Traceback (most recent call last):
  File "D:\anaconda3\envs\demucs\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\demucs\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\demucs2\demucs\__main__.py", line 328, in <module>
    main()
  File "C:\Users\USER\demucs2\demucs\__main__.py", line 244, in main
    train_loss, model_size = train_model(
  File "C:\Users\USER\demucs2\demucs\train.py", line 51, in train_model
    for idx, sources in enumerate(tq):
  File "D:\anaconda3\envs\demucs\lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "D:\anaconda3\envs\demucs\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "D:\anaconda3\envs\demucs\lib\site-packages\torch\utils\data\dataloader.py", line 1325, in _next_data
    return self._process_data(data)
  File "D:\anaconda3\envs\demucs\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "D:\anaconda3\envs\demucs\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "D:\anaconda3\envs\demucs\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda3\envs\demucs\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\envs\demucs\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\USER\demucs2\demucs\repitch.py", line 55, in __getitem__
    stream = repitch(
  File "C:\Users\USER\demucs2\demucs\repitch.py", line 89, in repitch
    sp.run(command, capture_output=True, input=in_.getvalue(), check=True)
  File "D:\anaconda3\envs\demucs\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\anaconda3\envs\demucs\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\anaconda3\envs\demucs\lib\subprocess.py", line 1327, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

**Comment by adefossez** [comment]
you do not have soundstretch install, please follow the instructions in the readme.
we do not officially support windows for training though, so might be complex to install. you can also disable repitch augment with `augment.repitch.proba=0`.
