### ISSUE TITLE
Standalone Windows/MacOS builds

### ISSUE THREAD

**Issue by ferropop** [facebookresearch/demucs#603]
Hoping we can get Windows/MacOS standalone builds so we can integrate demucs into DAWs like REAPER / MaxMSP that allow coding/scripting.  Thank you !

**Comment by CarlGao4** [comment]
See https://github.com/CarlGao4/demucs/releases

**Comment by ferropop** [comment]
Thanks!

I’m however getting this error:

￼

And was hoping to get this built for MacOS ARM also if this is possible!  Happy to do it myself if there were basic instructions.

Your efforts are appreciated!


ＦＥＲＲＯ

**Comment by CarlGao4** [comment]
What is the error? I can't see it

**Comment by marzlevane** [comment]
Perhaps the same error that I'm getting:

    Traceback (most recent call last):
      File "demucs-standalone.py", line 5, in <module>
      File "demucs\separate.py", line 193, in main
      File "demucs\audio.py", line 260, in save_audio
    NameError: name 'ta' is not defined. Did you mean: 'tp'?
    [27588] Failed to execute script 'demucs-standalone' due to unhandled exception!

Seems torchaudio was removed, but not the calls to ta when saving wav-files.

**Comment by jsammarco** [comment]
> Perhaps the same error that I'm getting:
> 
> ```
> Traceback (most recent call last):
>   File "demucs-standalone.py", line 5, in <module>
>   File "demucs\separate.py", line 193, in main
>   File "demucs\audio.py", line 260, in save_audio
> NameError: name 'ta' is not defined. Did you mean: 'tp'?
> [27588] Failed to execute script 'demucs-standalone' due to unhandled exception!
> ```
> 
> Seems torchaudio was removed, but not the calls to ta when saving wav-files.

Same here. Any way to fix it? Couldn't get conda install to work either. No audio back-end error on conda install that I couldn't fix.
