### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by imRig** [facebookresearch/demucs#67]
I tried to separate a track and this popped up. I've succesfully separated tracks in the past, so this is really weird.

![imagen](https://user-images.githubusercontent.com/58605807/71731949-c9596200-2e24-11ea-8ae3-ddb3d79bc560.png)

If someone could help me, I would be verry happy!

Thanks!

**Comment by adefossez** [comment]
You forgot to run `conda activate demucs` first :)

**Comment by VicentBello** [comment]
i have the same problem ! but i have all ready install pytorch and torchvision. 

Downloading and Extracting Packages
pillow-6.2.1         | 640 KB    | ######################################### | 100%
libtiff-4.1.0        | 737 KB    | ######################################### | 100%
torchvision-0.4.2    | 6.1 MB    | ######################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(demucs) C:\Anaconda3>python.exe -m demucs.separate --dl C:\CANCIONES_PARA_PARTIR\NOPUEDOCALLAR.mp3
Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\demucs\separate.py", line 13, in <module>
    import torch as th
ModuleNotFoundError: No module named 'torch'

i have no idea about programation and really need help with this.  thanks

**Comment by imedina7** [comment]
Hi! How is it going?
Had the same issue, it turned out I wasn't on the Anaconda Prompt (you can make sure if it is installed and working following [this guide](https://docs.anaconda.com/anaconda/install/verify-install/)), and didn't execute the first command in the [Requirements](https://github.com/facebookresearch/demucs#requirements) section of the README.

I hope this is useful.

**Comment by Andrew-afk** [comment]
It happened to me too. Just type:
conda install pytorch
and if gives you an error. Type:
conda uninstall pytorch
and then install it.

**Comment by ismathim** [comment]
So I followed these steps and it works:
>conda install pytorch torchvision -c pytorch
>pip3 install torch torchvision

**Comment by sebgilmour** [comment]
You can't just install the package, you need to specify the channel. So

`conda install -c pytorch pytorch`
or
`conda install -c pytorch pytorch=x.y.z` where x.y.z is the version you want
