### ISSUE TITLE
help/ayuda!! ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by VicentBello** [facebookresearch/demucs#69]
estoy instalando y tratando de correr el programa pero estoy atascado en con esto

ModuleNotFoundError: No module named 'torch'

anteriormente me había aparecido e instale:

(demucs) C:\Anaconda3>conda install pytorch

luego apareció lo mismo e instale:

(demucs) C:\Anaconda3>conda install torchvision -c pytorch

pero ahora la respuesta al pedir separar un tema es la misma:

(demucs) C:\Anaconda3>python.exe -m demucs.separate --dl C:\CANCIONES_PARA_PARTIR\NOPUEDOCALLAR.mp3
Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\demucs\separate.py", line 13, in <module>
    import torch as th
ModuleNotFoundError: No module named 'torch'

les estaría siempre agradecido por su ayuda ! no se nada de programación, pero como músico ansío poder usar esta herramienta

**Comment by adefossez** [comment]
Can you do
```
conda activate demucs
conda uninstall pytorch
conda install pytorch -c pytorch
```
and try again?

**Comment by VicentBello** [comment]
i tryed and still 


(base) C:\WINDOWS\system32>cd..

(base) C:\Windows>cd..

(base) C:\>cd anaconda3

(base) C:\Anaconda3>conda activate demucs

(demucs) C:\Anaconda3>conda uninstall pytorch
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.0
  latest version: 4.8.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Anaconda3\envs\demucs

  removed specs:
    - pytorch


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    setuptools-44.0.0          |           py37_0         526 KB
    ------------------------------------------------------------
                                           Total:         526 KB

The following packages will be REMOVED:

  _pytorch_select-1.1.0-cpu
  cffi-1.13.2-py37h7a1dbc1_0
  cudatoolkit-10.1.243-h74a9793_0
  freetype-2.9.1-ha9979f8_1
  jpeg-9b-hb83a4c4_2
  libpng-1.6.37-h2a8f88b_0
  libtiff-4.1.0-h56a325e_0
  ninja-1.9.0-py37h74a9793_0
  olefile-0.46-py37_0
  pillow-6.2.1-py37hdc69c19_0
  pycparser-2.19-py37_0
  pytorch-1.3.1-cpu_py37h9f948e0_0
  tk-8.6.8-hfa6e2cd_0
  torchvision-0.4.2-py37_cu101
  xz-5.2.4-h2fa13f4_4
  zlib-1.2.11-h62dcd97_3
  zstd-1.3.7-h508b16e_0

The following packages will be UPDATED:

  setuptools                                  42.0.2-py37_0 --> 44.0.0-py37_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
setuptools-44.0.0    | 526 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(demucs) C:\Anaconda3>conda install pytorch -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.0
  latest version: 4.8.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Anaconda3\envs\demucs

  added / updated specs:
    - pytorch


The following NEW packages will be INSTALLED:

  cffi               pkgs/main/win-64::cffi-1.13.2-py37h7a1dbc1_0
  cudatoolkit        pkgs/main/win-64::cudatoolkit-10.1.243-h74a9793_0
  ninja              pkgs/main/win-64::ninja-1.9.0-py37h74a9793_0
  pycparser          pkgs/main/win-64::pycparser-2.19-py37_0
  pytorch            pytorch/win-64::pytorch-1.3.1-py3.7_cuda101_cudnn7_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(demucs) C:\Anaconda3>python.exe -m demucs.separate -d cpu --dl C:\CANCIONES_PARA_PARTIR\NOPUEDOCALLAR.mp3
Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\demucs\separate.py", line 13, in <module>
    import torch as th
ModuleNotFoundError: No module named 'torch'

(demucs) C:\Anaconda3>

**Comment by Tenacius-collab** [comment]
> 
> 
> estoy instalando y tratando de correr el programa pero estoy atascado en con esto
> 
> ModuleNotFoundError: No module named 'torch'
> 
> anteriormente me había aparecido e instale:
> 
> (demucs) C:\Anaconda3>conda install pytorch
> 
> luego apareció lo mismo e instale:
> 
> (demucs) C:\Anaconda3>conda install torchvision -c pytorch
> 
> pero ahora la respuesta al pedir separar un tema es la misma:
> 
> (demucs) C:\Anaconda3>python.exe -m demucs.separate --dl C:\CANCIONES_PARA_PARTIR\NOPUEDOCALLAR.mp3
> Traceback (most recent call last):
> File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "C:\Anaconda3\demucs\separate.py", line 13, in
> import torch as th
> ModuleNotFoundError: No module named 'torch'
> 
> les estaría siempre agradecido por su ayuda ! no se nada de programación, pero como músico ansío poder usar esta herramienta

Hay que activar demucs, cada vez que se reinicia el PC. Con la linea "conda activate demucs".


>conda activate demucs
>(demucs) C:\Anaconda3>python.exe -m demucs.separate --dl C:\CANCIONES_PARA_PARTIR\NOPUEDOCALLAR.mp3

**Comment by VicentBello** [comment]
nada aun :/ sigue con el 
ModuleNotFoundError: No module named 'torch'

pienso volver a instalar todo desde cero
la verdad es que no son muy claras las instruccuiones para simples musicos como yo

**Comment by adefossez** [comment]
@VicentBello can you try running
```
python.exe
```
this should get you into the python console and from there type in
```
import sys
print(sys.executable)
```
and tell me what path is displayed? I'm guessing you might have another Python installation that is conflicting with the conda one, although it seems quite strange.

**Comment by VicentBello** [comment]
(base) C:\WINDOWS\system32>python.exe
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>>
>>> print(sys.executable)
C:\Anaconda3\python.exe

eso es todo lo que aparece

**Comment by oinarivibes** [comment]
> @VicentBello can you try running
> 
> ```
> python.exe
> ```
> 
> this should get you into the python console and from there type in
> 
> ```
> import sys
> print(sys.executable)
> ```
> 
> and tell me what path is displayed? I'm guessing you might have another Python installation that is conflicting with the conda one, although it seems quite strange.

Hi! . I have the same issue in MAC . Is there any solution ?
Salutes

**Comment by KnightRlex** [comment]
> 
> 
> > estoy instalando y tratando de correr el programa pero estoy atascado en con esto
> > ModuleNotFoundError: No module named 'torch'
> > anteriormente me había aparecido e instale:
> > (demucs) C:\Anaconda3>conda install pytorch
> > luego apareció lo mismo e instale:
> > (demucs) C:\Anaconda3>conda install torchvision -c pytorch
> > pero ahora la respuesta al pedir separar un tema es la misma:
> > (demucs) C:\Anaconda3>python.exe -m demucs.separate --dl C:\CANCIONES_PARA_PARTIR\NOPUEDOCALLAR.mp3
> > Traceback (most recent call last):
> > File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
> > "**main**", mod_spec)
> > File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
> > exec(code, run_globals)
> > File "C:\Anaconda3\demucs\separate.py", line 13, in
> > import torch as th
> > ModuleNotFoundError: No module named 'torch'
> > les estaría siempre agradecido por su ayuda ! no se nada de programación, pero como músico ansío poder usar esta herramienta
> 
> Hay que activar demucs, cada vez que se reinicia el PC. Con la linea "conda activate demucs".
> 
> > conda activate demucs
> > (demucs) C:\Anaconda3>python.exe -m demucs.separate --dl C:\CANCIONES_PARA_PARTIR\NOPUEDOCALLAR.mp3

Me funciono tu comentario amigo.

**Comment by xserrat** [comment]
Hi! I've just created a repository to dockerize the environment in order to execute the script in a more easy way. Checkout https://github.com/xserrat/docker-facebook-demucs if you're interested in.
