### ISSUE TITLE
ImportError: DLL load failed: El sistema operativo no puede ejecutar %1.

### ISSUE THREAD

**Issue by klauz996** [facebookresearch/demucs#77]
ImportError: DLL load failed: El sistema operativo no puede ejecutar %1.

**Comment by kerner93** [comment]
conda uptade --all

**Comment by voltax93** [comment]
hello, I have the same problem, `conda update --all` doesnt work for me, anyone can help me?

**Comment by 54n71** [comment]
> hello, I have the same problem, `conda update --all` doesnt work for me, anyone can help me pls?

The command **conda update --all**  doesn't work for me either

**Comment by 54n71** [comment]
> hello, I have the same problem, `conda update --all` doesnt work for me, anyone can help me pls?


I fixed the problem, I had written ### **conda uptade --all** and it was **### conda update --all**

**Comment by 54n71** [comment]
> > hello, I have the same problem, `conda update --all` doesnt work for me, anyone can help me pls?
> 
> The command **conda update --all** doesn't work for me either

Now it appears to me: ** ImportError: DLL load failed: Error en una rutina de inicialización de biblioteca de vínculos dinámicos (DLL).**

**Comment by ZaileVicioux** [comment]
I have the same problem, pls help

**Comment by 54n71** [comment]
> I have the same problem, pls help
I already solved it, I followed the steps (Windows)
https://youtu.be/ufjzCLOqmog

**Comment by kerner93** [comment]
Ejecuta Anaconda como administrador y ejecuta los siguientes comandos

conda activate demucs

cd demucs

conda uptade --all

conda update -n base -c defaults conda

**Comment by walterjose4** [comment]
It works! But now I have this error: Torch not compiled with CUDA enabled

(demucs) PS D:\demucs> python.exe -m demucs.separate -d cuda --dl "D:\Audios\Natalia Lafourcade - Hasta la Raíz (Audio)-iHSnLRrEC10.webm"
Traceback (most recent call last):
  File "C:\Users\pc\.conda\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\pc\.conda\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\demucs\demucs\separate.py", line 226, in <module>
    main()
  File "D:\demucs\demucs\separate.py", line 188, in main
    model = load_model(model_path).to(args.device)
  File "C:\Users\pc\.conda\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 607, in to
    return self._apply(convert)
  File "C:\Users\pc\.conda\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 354, in _apply
    module._apply(fn)
  File "C:\Users\pc\.conda\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 354, in _apply
    module._apply(fn)
  File "C:\Users\pc\.conda\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 354, in _apply
    module._apply(fn)
  File "C:\Users\pc\.conda\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 376, in _apply
    param_applied = fn(param)
  File "C:\Users\pc\.conda\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 605, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "C:\Users\pc\.conda\envs\demucs\lib\site-packages\torch\cuda\__init__.py", line 186, in _lazy_init
    _check_driver()
  File "C:\Users\pc\.conda\envs\demucs\lib\site-packages\torch\cuda\__init__.py", line 61, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
(demucs) PS D:\demucs>
