### ISSUE TITLE
Import Error: DLL load failed

### ISSUE THREAD

**Issue by ZaileVicioux** [facebookresearch/demucs#84]
I tryed to separate one song and then this popped up:
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Sele\demucs\demucs\separate.py", line 13, in <module>
>     import torch as th
>   File "C:\ProgramData\Anaconda3\lib\site-packages\torch\__init__.py", line 81, in <module>
>     from torch._C import *
> ImportError: DLL load failed: Error en una rutina de inicialización de biblioteca de vínculos dinámicos (DLL).

**Comment by adefossez** [comment]
Can you try `conda install -c defaults intel-openmp -f`
see https://github.com/pytorch/pytorch/issues/7579
and https://github.com/facebookresearch/demucs/issues/76

**Comment by somedaygone** [comment]
I just got this same error. I forgot to issue this command first: `conda activate demucs` 
Afterwards it worked as expected.
