### ISSUE TITLE
missing libffi-806b1a9d.so.6.0.4

### ISSUE THREAD

**Issue by panxin801** [facebookresearch/demucs#96]
```python
python3 -m demucs -b 4  --musdb musDB/
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/demucs/demucs/__main__.py", line 19, in <module>
    from .compressed import StemsSet, build_musdb_metadata, get_musdb_tracks
  File "/root/demucs/demucs/compressed.py", line 10, in <module>
    import musdb
  File "/root/.local/lib/python3.6/site-packages/musdb/__init__.py", line 1, in <module>
    from .audio_classes import MultiTrack, Source, Target
  File "/root/.local/lib/python3.6/site-packages/musdb/audio_classes.py", line 2, in <module>
    import soundfile as sf
  File "/root/.python/python3.6/dist-packages/soundfile.py", line 17, in <module>
    from _soundfile import ffi as _ffi
  File "/root/.python/python3.6/dist-packages/_soundfile.py", line 2, in <module>
    import _cffi_backend
ImportError: libffi-806b1a9d.so.6.0.4: cannot open shared object file: No such file or directory
```
Hellos sir, this is the error this time. It seems I miss the file, however after search I have got no place to download this file. At the same time, I am not sure if this error causes by soundfile-this lib's version ?

**Comment by adefossez** [comment]
Hey @panxin801 , what OS are you running?  Could try to install cffi with conda: `conda install -c conda-forge cffi` ?

**Comment by panxin801** [comment]
Hi, I'm running with ubuntu16.04+python3.6 and Anaconda3+python3.7. By now I give up the python3.6 env and have my python3.7 preparation done. Thank you sir. Oh by the way, when I meet this error, I'm sure I have cffi installed with my python 3.6
